// Package mwsgpthttp provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package mwsgpthttp

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for ErrorResponseErrorCode.
const (
	BADREQUEST    ErrorResponseErrorCode = "BAD_REQUEST"
	FORBIDDEN     ErrorResponseErrorCode = "FORBIDDEN"
	INTERNALERROR ErrorResponseErrorCode = "INTERNAL_ERROR"
	MODELERROR    ErrorResponseErrorCode = "MODEL_ERROR"
	NOTFOUND      ErrorResponseErrorCode = "NOT_FOUND"
	RATELIMITED   ErrorResponseErrorCode = "RATE_LIMITED"
	UNAUTHORIZED  ErrorResponseErrorCode = "UNAUTHORIZED"
)

// Valid indicates whether the value is a known member of the ErrorResponseErrorCode enum.
func (e ErrorResponseErrorCode) Valid() bool {
	switch e {
	case BADREQUEST:
		return true
	case FORBIDDEN:
		return true
	case INTERNALERROR:
		return true
	case MODELERROR:
		return true
	case NOTFOUND:
		return true
	case RATELIMITED:
		return true
	case UNAUTHORIZED:
		return true
	default:
		return false
	}
}

// Defines values for MessageRole.
const (
	Assistant MessageRole = "assistant"
	System    MessageRole = "system"
	User      MessageRole = "user"
)

// Valid indicates whether the value is a known member of the MessageRole enum.
func (e MessageRole) Valid() bool {
	switch e {
	case Assistant:
		return true
	case System:
		return true
	case User:
		return true
	default:
		return false
	}
}

// ChatRequest defines model for ChatRequest.
type ChatRequest struct {
	// MaxTokens Максимальная длина ответа в токенах
	MaxTokens *int `json:"maxTokens,omitempty"`

	// Messages История сообщений
	Messages []Message `json:"messages"`

	// Model ID модели (если не указан, используется по умолчанию)
	Model *string `json:"model,omitempty"`

	// SystemPrompt Системный промпт (альтернатива message с role=system)
	SystemPrompt *string `json:"systemPrompt,omitempty"`

	// Temperature Креативность ответов (0 = точные, 1 = творческие)
	Temperature *float32 `json:"temperature,omitempty"`
}

// ChatResponse defines model for ChatResponse.
type ChatResponse struct {
	// Id ID ответа
	Id      *string `json:"id,omitempty"`
	Message Message `json:"message"`

	// Model Использованная модель
	Model *string    `json:"model,omitempty"`
	Usage TokenUsage `json:"usage"`
}

// EmbeddingData defines model for EmbeddingData.
type EmbeddingData struct {
	// Embedding Вектор размерности 1024
	Embedding []float32 `json:"embedding"`

	// Index Индекс в исходном массиве
	Index int `json:"index"`
}

// EmbeddingsRequest defines model for EmbeddingsRequest.
type EmbeddingsRequest struct {
	// Input Текст или массив текстов для векторизации
	Input EmbeddingsRequest_Input `json:"input"`

	// Model ID модели для эмбеддингов
	Model *string `json:"model,omitempty"`
}

// EmbeddingsRequestInput0 defines model for .
type EmbeddingsRequestInput0 = string

// EmbeddingsRequestInput1 defines model for .
type EmbeddingsRequestInput1 = []string

// EmbeddingsRequest_Input Текст или массив текстов для векторизации
type EmbeddingsRequest_Input struct {
	union json.RawMessage
}

// EmbeddingsResponse defines model for EmbeddingsResponse.
type EmbeddingsResponse struct {
	Embeddings []EmbeddingData `json:"embeddings"`
	Model      *string         `json:"model,omitempty"`
	Usage      TokenUsage      `json:"usage"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		Code ErrorResponseErrorCode `json:"code"`

		// Details Технические детали
		Details *string `json:"details,omitempty"`

		// Message Человекочитаемое сообщение
		Message string `json:"message"`
	} `json:"error"`
}

// ErrorResponseErrorCode defines model for ErrorResponse.Error.Code.
type ErrorResponseErrorCode string

// GenerateRequest defines model for GenerateRequest.
type GenerateRequest struct {
	MaxTokens *int `json:"maxTokens,omitempty"`

	// Model ID модели
	Model *string `json:"model,omitempty"`

	// Prompt Текст для продолжения
	Prompt string `json:"prompt"`

	// StopSequences Стоп-слова для остановки генерации
	StopSequences *[]string `json:"stopSequences,omitempty"`
	Temperature   *float32  `json:"temperature,omitempty"`
}

// GenerateResponse defines model for GenerateResponse.
type GenerateResponse struct {
	Id    *string `json:"id,omitempty"`
	Model *string `json:"model,omitempty"`

	// Text Сгенерированный текст
	Text  string     `json:"text"`
	Usage TokenUsage `json:"usage"`
}

// Message defines model for Message.
type Message struct {
	// Content Текст сообщения
	Content string `json:"content"`

	// Role Роль отправителя
	Role MessageRole `json:"role"`
}

// MessageRole Роль отправителя
type MessageRole string

// ModelInfo defines model for ModelInfo.
type ModelInfo struct {
	// Id Идентификатор модели
	Id string `json:"id"`

	// Name Отображаемое имя
	Name string `json:"name"`

	// Provider Провайдер модели
	Provider string `json:"provider"`
}

// ModelsResponse defines model for ModelsResponse.
type ModelsResponse struct {
	Models []ModelInfo `json:"models"`
}

// TokenUsage defines model for TokenUsage.
type TokenUsage struct {
	// CompletionTokens Токенов в ответе
	CompletionTokens int `json:"completionTokens"`

	// PromptTokens Токенов в запросе
	PromptTokens int `json:"promptTokens"`

	// TotalTokens Всего токенов
	TotalTokens int `json:"totalTokens"`
}

// PostGptChatJSONRequestBody defines body for PostGptChat for application/json ContentType.
type PostGptChatJSONRequestBody = ChatRequest

// PostGptChatStreamJSONRequestBody defines body for PostGptChatStream for application/json ContentType.
type PostGptChatStreamJSONRequestBody = ChatRequest

// PostGptEmbeddingsJSONRequestBody defines body for PostGptEmbeddings for application/json ContentType.
type PostGptEmbeddingsJSONRequestBody = EmbeddingsRequest

// PostGptGenerateJSONRequestBody defines body for PostGptGenerate for application/json ContentType.
type PostGptGenerateJSONRequestBody = GenerateRequest

// AsEmbeddingsRequestInput0 returns the union data inside the EmbeddingsRequest_Input as a EmbeddingsRequestInput0
func (t EmbeddingsRequest_Input) AsEmbeddingsRequestInput0() (EmbeddingsRequestInput0, error) {
	var body EmbeddingsRequestInput0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmbeddingsRequestInput0 overwrites any union data inside the EmbeddingsRequest_Input as the provided EmbeddingsRequestInput0
func (t *EmbeddingsRequest_Input) FromEmbeddingsRequestInput0(v EmbeddingsRequestInput0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmbeddingsRequestInput0 performs a merge with any union data inside the EmbeddingsRequest_Input, using the provided EmbeddingsRequestInput0
func (t *EmbeddingsRequest_Input) MergeEmbeddingsRequestInput0(v EmbeddingsRequestInput0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEmbeddingsRequestInput1 returns the union data inside the EmbeddingsRequest_Input as a EmbeddingsRequestInput1
func (t EmbeddingsRequest_Input) AsEmbeddingsRequestInput1() (EmbeddingsRequestInput1, error) {
	var body EmbeddingsRequestInput1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmbeddingsRequestInput1 overwrites any union data inside the EmbeddingsRequest_Input as the provided EmbeddingsRequestInput1
func (t *EmbeddingsRequest_Input) FromEmbeddingsRequestInput1(v EmbeddingsRequestInput1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmbeddingsRequestInput1 performs a merge with any union data inside the EmbeddingsRequest_Input, using the provided EmbeddingsRequestInput1
func (t *EmbeddingsRequest_Input) MergeEmbeddingsRequestInput1(v EmbeddingsRequestInput1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t EmbeddingsRequest_Input) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *EmbeddingsRequest_Input) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Отправить сообщение в чат
	// (POST /gpt/chat)
	PostGptChat(c *gin.Context)
	// Отправить сообщение в чат (streaming)
	// (POST /gpt/chat/stream)
	PostGptChatStream(c *gin.Context)
	// Получить эмбеддинги текста
	// (POST /gpt/embeddings)
	PostGptEmbeddings(c *gin.Context)
	// Сгенерировать текст
	// (POST /gpt/generate)
	PostGptGenerate(c *gin.Context)
	// Получить список доступных моделей
	// (GET /gpt/models)
	GetGptModels(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// PostGptChat operation middleware
func (siw *ServerInterfaceWrapper) PostGptChat(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostGptChat(c)
}

// PostGptChatStream operation middleware
func (siw *ServerInterfaceWrapper) PostGptChatStream(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostGptChatStream(c)
}

// PostGptEmbeddings operation middleware
func (siw *ServerInterfaceWrapper) PostGptEmbeddings(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostGptEmbeddings(c)
}

// PostGptGenerate operation middleware
func (siw *ServerInterfaceWrapper) PostGptGenerate(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostGptGenerate(c)
}

// GetGptModels operation middleware
func (siw *ServerInterfaceWrapper) GetGptModels(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetGptModels(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/gpt/chat", wrapper.PostGptChat)
	router.POST(options.BaseURL+"/gpt/chat/stream", wrapper.PostGptChatStream)
	router.POST(options.BaseURL+"/gpt/embeddings", wrapper.PostGptEmbeddings)
	router.POST(options.BaseURL+"/gpt/generate", wrapper.PostGptGenerate)
	router.GET(options.BaseURL+"/gpt/models", wrapper.GetGptModels)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZ3W4bxxV+lcG4FzawlijHblACQSFHssoi+qlEwUAdwViTI2pT7k92h4JVQ4Ao1XUC",
	"KxLg5sIoirrJTW9pRrRXNEW9wplX6JMU58yS3OUuKaqxjALxnXa52nPmzPd955uzT3jJtT3XEY4MeP4J",
	"D0pbwjbpz8+3TLkqvq6JQOKl57ue8KUl6EfbfFx0/yQcuiiLTbNWlTw/k8vlDF4WQcm3PGm5Ds9z+Ac0",
	"oK3qEEIHGvBOHcIZNNQxgxN4ByFeMOiqfWhCS+3jRZOpfehCG1r05FNuYDjLrtk8fzv3m18b3LYcfTlj",
	"cLnjCZ7nliNFRfh81+C2CAKzIqLUErm8VHV8t9qDUB0zVYcudOG1+pZChXDKDW5JYdO//soXmzzPr00P",
	"KjQdlWd6UYfAaFF80/fNHYrulkU1Hbowx6ADXTiBFi6bXYeWqtNfcAYtpg6gDQ14Cw04MxiEqg7n0KVq",
	"vVUHWBlVx5qdQxef7dBvz/BpCNXRDW5w8di0vSqmYsvgpunsmLyfXCB9y6lgdsFOIIW94ru2JzPq8wNG",
	"VvvQgg6cqedwyuBc7UEXOnCu9tl1vYH4gNqjzdmHEJrQYFHNmaoz362Kz3ScZF7wo3rO9LKgBW97ARqq",
	"juiI4p6p/ay8pbA94Zuy5osE4nJTn6YA93e1B61+bmfQxVerwzjKutBk13PsM0KaekaptAw2o+80ESHq",
	"Ge1QG0Jo4To2Xd82Jc/zzapryjgmb8UAmevn7tTsR4jHXYP74uua5Ysyzz8YgHOj/6T76CtRkrhKTbnA",
	"c51ApDlnlbNhFSNPot6+CLyHM7c+yapnlMYlcD4C10ipAVSxsATKiOJ9xKvDiSFamyQxEp91nVt2hXnv",
	"TVmFnrcfiXLZcipzpjTTlRa9nzPW+wJa0NYiwtQecbYT0YGABiGbyd26HVeSFHSGIJIWEcspi8dZxYYz",
	"qmdb1VEniTVPqcZnSFIseEQnRES85Lm0Ug7VTcc0YosfW7lgZG+wHK+WJS4/6sTVPoNQK18sW0bsb2t9",
	"xqWdwDtEUHNQbghRH9VfIYQwKSyv6EfigMFISNssUtrGb7nBXUcsb/L8gycptD0Z7FJacxKbspHkQKQ/",
	"/FFF3LSRYuPlPlqO+g468BpacAIn1Pt+wsUmFtN/4VA+qd3CIl+0Q6OkpL/HesMmaXlJyoxrfBev5eeT",
	"PLaAsTz3fdcfUwb8OX275JbpYeGgpD/gd2fnHq7O/2F9fq3IDb6+NLte/N3yauGP83Pc4PeWV+8W5ubm",
	"l7jBl5aLD+8try/h/dXZ4vzDLwqLhSI9Vlgqzq8uzX7xcH51dXmVG3xxeW6+d7URB0AyWqpyZSFNqxpk",
	"80s9JUMQa13EA2wNCMMLOsHQ+/5N2O1qClKbDOlFLUJ2K22fEoLDC862WbXKjHDBAk+UrE1LlC9ENlV/",
	"kFd6W4ehQJuYtfsLwkHPIC7rYu/kLus4J/J8E3dAb5Q9iyloJI/anZ2Qp3qjt0EdJ8URG3RbHaDQaqOA",
	"7VlbrxDtFiX3Tsss+8/e90x9h3qb6R6l661hMZ1Spr3+gcT7/CY5W7IC/UR1b2xQn2oiNBn8RKlg68wQ",
	"9Qf8S4cb/Nq1a7i1k4r0BUbxPXm4aH/GQ268ixvsT0U4I01aWlHHwUaKx9meflDokOASWTTCwKDtvhfU",
	"MBQEbLs9z92ODg+H6qh3bFDP1VNGDvEA2lNTU1fRH6gW4zrD4kD2hsXfkcIZz75h5SPKpdaAB6GM1/xL",
	"m2Xt28/JQjZJWdEmE3ejtqPPULQK4XODm0FgBdJ04sgboaEU2uivJbMACK6Cs+lOdtCAlyRjuPOh+guE",
	"6LIiF/w/aZxj2lnF+ScpyGuqyptYr4EQOkPCtlhcY7OjFXTbKgs/I8KrPgVOqTWOyX/x/trFPgwbGi0m",
	"FnVkvcdYMiL75HZssH0pERw+D+kXZ+UUI1AGD7AKWLV4ixwiRG9KQ469GT+KJrzA7VtZXVPL6CXe/hYa",
	"uuGpevL9M3ey3i9daVZHvv4FvgT9d3zaNGTG73x64akpsQgjXbVkGplmJhClmm/JnTXcWl38u8L0hT9b",
	"k1t49Yiu7vWa1+/vozEkIJDJpl8HQN2S0uO7u3SK1OxONQSUYdSceuyYhcUN+1Q4jWRfj8nYbOFm7Cx/",
	"DB0Ip750Ii7RcE/t6TFVYpfUcwZttnh/jS2sFA1GPuU16d07dYxhG9AcPtupI4bmoCcCrwlTbXWA4PoG",
	"QrwB7SkyB9KSxNOFlSJbE/62VRJsdqXADb4t/ECvdmYqN5VDNLiecEzP4nn+Cd0yuGfKLar2dMWT06Ut",
	"UztEN8gS/+8hJA/d1Uc2LUojq0bueKhqh+qIakY3SHngjZ6e6bqFsdnkUcZsEssSG5TpAV0rMaBTz3Vh",
	"XLJAlusUyjzPV9xALnjy8y2yPL42w3fd8s5QuzM9r2qV6P+mvwpw2b158EViFB8V7yYZIv2aoBta96je",
	"t3K59xw6ElWKndFRmrrCcZ3fNfjt95hG8qCZkcdds8z6JcLYMx8u9rpj1uSW61t/FmUMfudDLrzgSOE7",
	"ZpUYKnxG/5DQPRrMxBXvwcbuhsGDmm2b/k5vD2NOSR1mnD3pu8EzNCWoDGYloLMkYn4Dg/U5Ph1IX5j2",
	"VVMdb8I5iVeXTDC+5xRvtWg8fQINPKbjrdj8FgUiBthzEgM94AvpBrarZ5G7PoYOux7/VAKdG/3pV5Mh",
	"MxZWihcowpquxv+pLqCNnxbbwpE3B9s2iD1szdLsf9XbgaHp/y+Y/1fIPHZd75LlVG6MZmFy+DiChK+I",
	"JT0XMPiwQHwbjIrpc2FiSHym+XquWRZNHZp0VKX/Roq9HPV5LZrS1qm/NqLTTm+aRnqgP2CFdKNBTqUd",
	"HXfrsYMRjTPGMG8+Pr68Cualx/QfuC9nTKGz+PniEjv3kbOTcfYVIftAz2uRsemPDmGCQzGqxrg5IGwl",
	"GmqNoevfkrM8JFGCpNFX/no0/0vaVt33LiAl9V/U7z31TW/qkghi6GHTCfF0aLJI3nl/Ck7GcLI3ursi",
	"Rg4Poz8wH1ODySw2Tjwq/MjEiZiYWU/NyfjYtUe+iGcYdkC+wVyoImTm9+guvIUmYf3b6CxJTAqpU7fj",
	"x54WnOpTOPnHAzjvDWOHPuBHw8ijFFUWBDJFj7L4FaJ1aFiWjdVRS/x4vvJ/bsdI4CcDL8l6DxDcmzXu",
	"6viYUEDhkznHBjbc4DW/yvN82vSs6e0Zvrux+98AAAD//w/bMV+VJgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
