// Package mwsgpthttp provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package mwsgpthttp

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for ErrorResponseErrorCode.
const (
	BADREQUEST    ErrorResponseErrorCode = "BAD_REQUEST"
	FORBIDDEN     ErrorResponseErrorCode = "FORBIDDEN"
	INTERNALERROR ErrorResponseErrorCode = "INTERNAL_ERROR"
	MODELERROR    ErrorResponseErrorCode = "MODEL_ERROR"
	NOTFOUND      ErrorResponseErrorCode = "NOT_FOUND"
	RATELIMITED   ErrorResponseErrorCode = "RATE_LIMITED"
	UNAUTHORIZED  ErrorResponseErrorCode = "UNAUTHORIZED"
)

// Valid indicates whether the value is a known member of the ErrorResponseErrorCode enum.
func (e ErrorResponseErrorCode) Valid() bool {
	switch e {
	case BADREQUEST:
		return true
	case FORBIDDEN:
		return true
	case INTERNALERROR:
		return true
	case MODELERROR:
		return true
	case NOTFOUND:
		return true
	case RATELIMITED:
		return true
	case UNAUTHORIZED:
		return true
	default:
		return false
	}
}

// Defines values for MessageRole.
const (
	Assistant MessageRole = "assistant"
	System    MessageRole = "system"
	User      MessageRole = "user"
)

// Valid indicates whether the value is a known member of the MessageRole enum.
func (e MessageRole) Valid() bool {
	switch e {
	case Assistant:
		return true
	case System:
		return true
	case User:
		return true
	default:
		return false
	}
}

// Defines values for ModelInfoFeatures.
const (
	Chat       ModelInfoFeatures = "chat"
	Completion ModelInfoFeatures = "completion"
	Embeddings ModelInfoFeatures = "embeddings"
	Streaming  ModelInfoFeatures = "streaming"
)

// Valid indicates whether the value is a known member of the ModelInfoFeatures enum.
func (e ModelInfoFeatures) Valid() bool {
	switch e {
	case Chat:
		return true
	case Completion:
		return true
	case Embeddings:
		return true
	case Streaming:
		return true
	default:
		return false
	}
}

// ChatRequest defines model for ChatRequest.
type ChatRequest struct {
	// MaxTokens Максимальная длина ответа в токенах
	MaxTokens *int `json:"maxTokens,omitempty"`

	// Messages История сообщений
	Messages []Message `json:"messages"`

	// Model ID модели (если не указан, используется по умолчанию)
	Model *string `json:"model,omitempty"`

	// SystemPrompt Системный промпт (альтернатива message с role=system)
	SystemPrompt *string `json:"systemPrompt,omitempty"`

	// Temperature Креативность ответов (0 = точные, 1 = творческие)
	Temperature *float32 `json:"temperature,omitempty"`
}

// ChatResponse defines model for ChatResponse.
type ChatResponse struct {
	// Id ID ответа
	Id      *string `json:"id,omitempty"`
	Message Message `json:"message"`

	// Model Использованная модель
	Model *string    `json:"model,omitempty"`
	Usage TokenUsage `json:"usage"`
}

// EmbeddingData defines model for EmbeddingData.
type EmbeddingData struct {
	// Embedding Вектор размерности 1024
	Embedding []float32 `json:"embedding"`

	// Index Индекс в исходном массиве
	Index int `json:"index"`
}

// EmbeddingsRequest defines model for EmbeddingsRequest.
type EmbeddingsRequest struct {
	// Input Текст или массив текстов для векторизации
	Input EmbeddingsRequest_Input `json:"input"`

	// Model ID модели для эмбеддингов
	Model *string `json:"model,omitempty"`
}

// EmbeddingsRequestInput0 defines model for .
type EmbeddingsRequestInput0 = string

// EmbeddingsRequestInput1 defines model for .
type EmbeddingsRequestInput1 = []string

// EmbeddingsRequest_Input Текст или массив текстов для векторизации
type EmbeddingsRequest_Input struct {
	union json.RawMessage
}

// EmbeddingsResponse defines model for EmbeddingsResponse.
type EmbeddingsResponse struct {
	Embeddings []EmbeddingData `json:"embeddings"`
	Model      *string         `json:"model,omitempty"`
	Usage      TokenUsage      `json:"usage"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		Code ErrorResponseErrorCode `json:"code"`

		// Details Технические детали
		Details *string `json:"details,omitempty"`

		// Message Человекочитаемое сообщение
		Message string `json:"message"`
	} `json:"error"`
}

// ErrorResponseErrorCode defines model for ErrorResponse.Error.Code.
type ErrorResponseErrorCode string

// GenerateRequest defines model for GenerateRequest.
type GenerateRequest struct {
	MaxTokens *int `json:"maxTokens,omitempty"`

	// Model ID модели
	Model *string `json:"model,omitempty"`

	// Prompt Текст для продолжения
	Prompt string `json:"prompt"`

	// StopSequences Стоп-слова для остановки генерации
	StopSequences *[]string `json:"stopSequences,omitempty"`
	Temperature   *float32  `json:"temperature,omitempty"`
}

// GenerateResponse defines model for GenerateResponse.
type GenerateResponse struct {
	Id    *string `json:"id,omitempty"`
	Model *string `json:"model,omitempty"`

	// Text Сгенерированный текст
	Text  string     `json:"text"`
	Usage TokenUsage `json:"usage"`
}

// Message defines model for Message.
type Message struct {
	// Content Текст сообщения
	Content string `json:"content"`

	// Role Роль отправителя
	Role MessageRole `json:"role"`
}

// MessageRole Роль отправителя
type MessageRole string

// ModelInfo defines model for ModelInfo.
type ModelInfo struct {
	// ContextLength Максимальная длина контекста в токенах
	ContextLength *int `json:"contextLength,omitempty"`

	// Description Описание модели
	Description *string `json:"description,omitempty"`

	// Features Поддерживаемые функции
	Features *[]ModelInfoFeatures `json:"features,omitempty"`

	// Id Идентификатор модели
	Id string `json:"id"`

	// Name Отображаемое имя
	Name string `json:"name"`

	// Provider Провайдер модели
	Provider string `json:"provider"`
}

// ModelInfoFeatures defines model for ModelInfo.Features.
type ModelInfoFeatures string

// ModelsResponse defines model for ModelsResponse.
type ModelsResponse struct {
	Models []ModelInfo `json:"models"`
}

// TokenUsage defines model for TokenUsage.
type TokenUsage struct {
	// CompletionTokens Токенов в ответе
	CompletionTokens int `json:"completionTokens"`

	// PromptTokens Токенов в запросе
	PromptTokens int `json:"promptTokens"`

	// TotalTokens Всего токенов
	TotalTokens int `json:"totalTokens"`
}

// PostGptChatJSONRequestBody defines body for PostGptChat for application/json ContentType.
type PostGptChatJSONRequestBody = ChatRequest

// PostGptChatStreamJSONRequestBody defines body for PostGptChatStream for application/json ContentType.
type PostGptChatStreamJSONRequestBody = ChatRequest

// PostGptEmbeddingsJSONRequestBody defines body for PostGptEmbeddings for application/json ContentType.
type PostGptEmbeddingsJSONRequestBody = EmbeddingsRequest

// PostGptGenerateJSONRequestBody defines body for PostGptGenerate for application/json ContentType.
type PostGptGenerateJSONRequestBody = GenerateRequest

// AsEmbeddingsRequestInput0 returns the union data inside the EmbeddingsRequest_Input as a EmbeddingsRequestInput0
func (t EmbeddingsRequest_Input) AsEmbeddingsRequestInput0() (EmbeddingsRequestInput0, error) {
	var body EmbeddingsRequestInput0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmbeddingsRequestInput0 overwrites any union data inside the EmbeddingsRequest_Input as the provided EmbeddingsRequestInput0
func (t *EmbeddingsRequest_Input) FromEmbeddingsRequestInput0(v EmbeddingsRequestInput0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmbeddingsRequestInput0 performs a merge with any union data inside the EmbeddingsRequest_Input, using the provided EmbeddingsRequestInput0
func (t *EmbeddingsRequest_Input) MergeEmbeddingsRequestInput0(v EmbeddingsRequestInput0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEmbeddingsRequestInput1 returns the union data inside the EmbeddingsRequest_Input as a EmbeddingsRequestInput1
func (t EmbeddingsRequest_Input) AsEmbeddingsRequestInput1() (EmbeddingsRequestInput1, error) {
	var body EmbeddingsRequestInput1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmbeddingsRequestInput1 overwrites any union data inside the EmbeddingsRequest_Input as the provided EmbeddingsRequestInput1
func (t *EmbeddingsRequest_Input) FromEmbeddingsRequestInput1(v EmbeddingsRequestInput1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmbeddingsRequestInput1 performs a merge with any union data inside the EmbeddingsRequest_Input, using the provided EmbeddingsRequestInput1
func (t *EmbeddingsRequest_Input) MergeEmbeddingsRequestInput1(v EmbeddingsRequestInput1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t EmbeddingsRequest_Input) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *EmbeddingsRequest_Input) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Отправить сообщение в чат
	// (POST /gpt/chat)
	PostGptChat(c *gin.Context)
	// Отправить сообщение в чат (streaming)
	// (POST /gpt/chat/stream)
	PostGptChatStream(c *gin.Context)
	// Получить эмбеддинги текста
	// (POST /gpt/embeddings)
	PostGptEmbeddings(c *gin.Context)
	// Сгенерировать текст
	// (POST /gpt/generate)
	PostGptGenerate(c *gin.Context)
	// Получить список доступных моделей
	// (GET /gpt/models)
	GetGptModels(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// PostGptChat operation middleware
func (siw *ServerInterfaceWrapper) PostGptChat(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostGptChat(c)
}

// PostGptChatStream operation middleware
func (siw *ServerInterfaceWrapper) PostGptChatStream(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostGptChatStream(c)
}

// PostGptEmbeddings operation middleware
func (siw *ServerInterfaceWrapper) PostGptEmbeddings(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostGptEmbeddings(c)
}

// PostGptGenerate operation middleware
func (siw *ServerInterfaceWrapper) PostGptGenerate(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostGptGenerate(c)
}

// GetGptModels operation middleware
func (siw *ServerInterfaceWrapper) GetGptModels(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetGptModels(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/gpt/chat", wrapper.PostGptChat)
	router.POST(options.BaseURL+"/gpt/chat/stream", wrapper.PostGptChatStream)
	router.POST(options.BaseURL+"/gpt/embeddings", wrapper.PostGptEmbeddings)
	router.POST(options.BaseURL+"/gpt/generate", wrapper.PostGptGenerate)
	router.GET(options.BaseURL+"/gpt/models", wrapper.GetGptModels)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xa3W4bxxV+lcG4Fw6wlijHbhoCQSFHisoi+qlEwUAdwViTI2pTcnezOxSsGgJEKa4S",
	"SJEANxdGUcRJbnpLM6K1okXyFc68Qp+kOGeW5C53SdGNZRSo77Q/nJ8z3/ed75zVE15wKq5jC1v6PPuE",
	"+4UtUTHpz0+3TLkqvqoKX+Kl6zmu8KQl6GHFfJx3/iJsuiiKTbNaljw7k8lkDF4UfsGzXGk5Ns9y+CfU",
	"oaVqEMAl1OG1OoY21NUpgzN4DQFeMOiofWhAU+3jRYOpfehAC5r05lNu4HRWpVrh2TuZj39r8Ipl68sZ",
	"g8sdV/Ast2wpSsLjuwavCN83SyJcWmwtz1UNx1Z7EKhTpmrQgQ68VN/SVAFccINbUlTop7/xxCbP8hvT",
	"gwhNh+GZXtRT4Gzh/KbnmTs0u1MU5eTUuTkGl9CBM2jittlNaKoa/QVtaDJ1AC2owznUoW0wCFQNutCh",
	"aJ2rA4yMqmHMutDBdy/p2SG+DYE6+YAbXDw2K24Zl1KR/i3T3jF5f3G+9Cy7hKvzd3wpKiueU3FlSnx+",
	"wpnVPjThEtrqCC4YdNUedOASumqf3dQHiC+oPTqcfQigAXUWxpypGvOcsvhEzxNfF/ysjpjeFjThvDdB",
	"XdUQHeG8bbWftm4pKq7wTFn1RAxxmamPEoD7h9qDZn9tbejg0Oo4irIONNjNDPuEkKYOaSlNg83oOw1E",
	"iDqkE2pBAE3cx6bjVUzJs3yz7JgyisnbEUBm+mu3q5VHiMddg3viq6rliSLPPhiAc6P/pvPoS1GQuEtN",
	"Od91bF8kOWcV02EVIU8s3p7w3Ycztz9Mi2e4jDfA+QhcI6UGUMXAEihDivcRr44nhmh1koWR+KzrtaVH",
	"mPdGSgv0fOWRKBYtuzRnSjMZadF7nLLfZ9CElhYRpvaIs5chHQhoELCZzO07USVJQGcIIkkRseyieJwW",
	"bGhTPFuqhjpJrHlKMW4jSTHgIZ0QEdGQZ5JKORQ3PacR2fzYyPkjc4Nlu9U0cflZL1ztMwi08kVWy4j9",
	"La3PuLUzeI0IagzCDQHqo/obBBDEheUFPSQOGIyEtMVCpa3/nhvcscXyJs8+eJJA25PBKSU1J3YoG3EO",
	"hPrDH5XErQpSbLzch9tR38ElvIQmnMEZ5b5fcLOxzfQHHFpP4rQwyFed0Cgp6Z+xPrBJUl6cMuMS39V7",
	"+fUkj2xgLM89z/HGhAEfJ28XnCK9LGyU9Af83uzcw9X5P63Pr+W5wdeXZtfzf1hezf15fo4b/LPl1Xu5",
	"ubn5JW7wpeX8w8+W15fw/upsfv7h57nFXJ5eyy3l51eXZj9/OL+6urzKDb64PDffu9qIAiA+WyJyRSFN",
	"q+yn80s9JUMQSV3EA0wNCMMrMsHQeP8i7HY0BSlNBjRQk5DdTNqnmODwnL1tlq0iI1ww3xUFa9MSxSuR",
	"TdEfrCt5rMNQoENMO/0FYaNnEG/qYu9m3tRxTuT5Js6A7ih7FlHQUB61OzsjT/VKH4M6jYsjJuiWOkCh",
	"1UYB07O2XgHaLVrcay2z7N973zP1HeptqnuUjruGwbQLqfb6JxLv7i1ytmQF+gvVubFOeaqB0GTwCy0F",
	"U2eKqD/gX9jc4Ddu3MCjnVSkrzCKb8nDheczHnLjXdzgfErCHmnSkoo6DjZSPE739INABwSX0KIRBgZp",
	"962ghqEgYNrtee5WWDwcq5Ne2aCO1FNGDvEAWlNTU9eRHygW4zLD4kD2hsXflsIez75h5SPKJfaAhVDK",
	"MD9qs6x9e5csZIOUFW0ycTdMO7qGol0Ijxvc9H3Ll6YdRd4IDaWpjf5eUgOA4MrZm86IEDyWnwu7JLdS",
	"djBJRY/n3o54uvS6vg+43818fDtNWWMzJxbyA3SpVK7r9DNabeFHDWXKY6dwro6w6EvUKH21QnNWJw3r",
	"GbTE6W4KEpk0GXxBI54R2l/pAhmTJtaYTH2tDqANrb7i9aWtd+yFLZImxHtZ0JBG3O740hNmJW7QRwti",
	"WtUIz2nHeD6B+hoCtMxhSfNfJSzbrKQh/Qc675cE8VcR44DAGcpSi/k1Njs6HW5bReGlRbqvZxc63qPX",
	"v3h/7WpTje6ENhOZdSR5xvhrUu7JvfWAi4kDHC5u9cBpa4qoYQqje2CK+p0hdetRk8qvRrSvEDN2d1KJ",
	"qnPiG4x+DnXtXlQtPv7M3bTxpSPN8sjhn+EgyNWoxAxVVnc/urIEjm3CSEYtvoxUZ+qLQtWz5M4aHq0O",
	"/j1hesKbrWotfURXn/WcyB/vo8snIFDFRE8HQN2S0uW7u9QS0FKdyO6oMphAapGaGYMb9KlwEeZw3fNk",
	"s7lbEdE7hUsIpr6wQy6Rrqs93XOMnZI6YtBii/fX2MJK3mBkOl9S8nqtTnHaOjSGC3V1wtDp9UTgJWGq",
	"pQ4QXN9AgDegNUVOT1qSeLqwkmdrwtu2CoLNruS4wbeF5+vdzkxlpjKIBscVtulaPMs/pFsGd025RdGe",
	"LrlymjQUWeD4aZn8+7i8a1EaGTUqdYaidqxOKGZpSk8Njkij+SSl0YxhiXQ9dbe1Geu2qiMdGIf8rOXY",
	"uSLP8hXHlwuu/FQnCU9XNvec4s6QdzFdt2wV6HfTX/o6e2q5uUqMon3/3ThDpFcVdEPrHsX7dibzlqcO",
	"RZXmTskoDR3hqM7vGvzOW1xGvGuQso57ZpH1Q4Rzz7y7uddtsyq3HM/6qyji5Hff5cZzthSebZaJocJj",
	"9IOY7lGXLap4DzZ2NwzuVysV09vpnWHE9qrjlEYCmcVDNCWoDGbJ7xujDZysz/Fp7YWum+p4E7okXh1y",
	"tjjOBd5q0reGM6irQxwn1oxHgYgAtktioLu1Ad3AdHUYlkqncMluRv0xXH7Qb2U2GDJjYSV/hSKs6Wj8",
	"j+oC1hTTYlvY8tbg2AZzD1uzJPtf9E5g6FPO/zH/r5F57Ga/0PhgNAvjneQRJHxBLOm5gMFXIuLbUI0Y",
	"6/i3NV+7mmVhC6lBfQf6NVLs+ahvpWHLvUb5tR5WO73WKOmB/hoZ0I06OZVW2LuoRQojqtTGMG8+Wpxd",
	"B/OS31zecV5O+aSQxs9nb3By7zk7GWdfELIPdPMdGZv8ghTEOBShaoSbA8KWwg7lGLr+Pd6YRRLFSBr+",
	"y0YtbObGbavOe1eQkvIv6vee+qbXQotNYugO0hnxdKhNTN55fwrOxnCy14e9JkYOf1l4x3xMdJnT2Dhx",
	"3/c9EydiYmo8NSejPfQe+UKe4bQD8g36QiUhU/+5oAPn0CCsfxvWksSkgDJ1K1r2NOFCV+HkHw+g2+us",
	"D/03RthZPklQZUEgU3Qri18jWoeaZelYHbXF9/WV92szRgw/KXiJx3uA4F6vcVfPjwvyafr4miMNG27w",
	"qlfmWT5tutb09gzf3dj9TwAAAP//Mj53I2IoAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
