// Package tableclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package tableclient

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// Defines values for CreateFieldRequestType.
const (
	CreateFieldRequestTypeAttachment   CreateFieldRequestType = "Attachment"
	CreateFieldRequestTypeCheckbox     CreateFieldRequestType = "Checkbox"
	CreateFieldRequestTypeCurrency     CreateFieldRequestType = "Currency"
	CreateFieldRequestTypeDateTime     CreateFieldRequestType = "DateTime"
	CreateFieldRequestTypeEmail        CreateFieldRequestType = "Email"
	CreateFieldRequestTypeMember       CreateFieldRequestType = "Member"
	CreateFieldRequestTypeMultiSelect  CreateFieldRequestType = "MultiSelect"
	CreateFieldRequestTypeNumber       CreateFieldRequestType = "Number"
	CreateFieldRequestTypePercent      CreateFieldRequestType = "Percent"
	CreateFieldRequestTypePhone        CreateFieldRequestType = "Phone"
	CreateFieldRequestTypeRating       CreateFieldRequestType = "Rating"
	CreateFieldRequestTypeSingleSelect CreateFieldRequestType = "SingleSelect"
	CreateFieldRequestTypeSingleText   CreateFieldRequestType = "SingleText"
	CreateFieldRequestTypeText         CreateFieldRequestType = "Text"
	CreateFieldRequestTypeURL          CreateFieldRequestType = "URL"
)

// Valid indicates whether the value is a known member of the CreateFieldRequestType enum.
func (e CreateFieldRequestType) Valid() bool {
	switch e {
	case CreateFieldRequestTypeAttachment:
		return true
	case CreateFieldRequestTypeCheckbox:
		return true
	case CreateFieldRequestTypeCurrency:
		return true
	case CreateFieldRequestTypeDateTime:
		return true
	case CreateFieldRequestTypeEmail:
		return true
	case CreateFieldRequestTypeMember:
		return true
	case CreateFieldRequestTypeMultiSelect:
		return true
	case CreateFieldRequestTypeNumber:
		return true
	case CreateFieldRequestTypePercent:
		return true
	case CreateFieldRequestTypePhone:
		return true
	case CreateFieldRequestTypeRating:
		return true
	case CreateFieldRequestTypeSingleSelect:
		return true
	case CreateFieldRequestTypeSingleText:
		return true
	case CreateFieldRequestTypeText:
		return true
	case CreateFieldRequestTypeURL:
		return true
	default:
		return false
	}
}

// Defines values for TableFieldType.
const (
	TableFieldTypeAttachment   TableFieldType = "Attachment"
	TableFieldTypeCheckbox     TableFieldType = "Checkbox"
	TableFieldTypeCurrency     TableFieldType = "Currency"
	TableFieldTypeDateTime     TableFieldType = "DateTime"
	TableFieldTypeEmail        TableFieldType = "Email"
	TableFieldTypeMember       TableFieldType = "Member"
	TableFieldTypeMultiSelect  TableFieldType = "MultiSelect"
	TableFieldTypeNumber       TableFieldType = "Number"
	TableFieldTypePercent      TableFieldType = "Percent"
	TableFieldTypePhone        TableFieldType = "Phone"
	TableFieldTypeRating       TableFieldType = "Rating"
	TableFieldTypeSingleSelect TableFieldType = "SingleSelect"
	TableFieldTypeSingleText   TableFieldType = "SingleText"
	TableFieldTypeText         TableFieldType = "Text"
	TableFieldTypeURL          TableFieldType = "URL"
)

// Valid indicates whether the value is a known member of the TableFieldType enum.
func (e TableFieldType) Valid() bool {
	switch e {
	case TableFieldTypeAttachment:
		return true
	case TableFieldTypeCheckbox:
		return true
	case TableFieldTypeCurrency:
		return true
	case TableFieldTypeDateTime:
		return true
	case TableFieldTypeEmail:
		return true
	case TableFieldTypeMember:
		return true
	case TableFieldTypeMultiSelect:
		return true
	case TableFieldTypeNumber:
		return true
	case TableFieldTypePercent:
		return true
	case TableFieldTypePhone:
		return true
	case TableFieldTypeRating:
		return true
	case TableFieldTypeSingleSelect:
		return true
	case TableFieldTypeSingleText:
		return true
	case TableFieldTypeText:
		return true
	case TableFieldTypeURL:
		return true
	default:
		return false
	}
}

// CreateFieldRequest defines model for CreateFieldRequest.
type CreateFieldRequest struct {
	Name     string                  `json:"name"`
	Property *map[string]interface{} `json:"property,omitempty"`
	Type     CreateFieldRequestType  `json:"type"`
}

// CreateFieldRequestType defines model for CreateFieldRequest.Type.
type CreateFieldRequestType string

// CreateRecordsRequest defines model for CreateRecordsRequest.
type CreateRecordsRequest struct {
	Records []struct {
		// Fields Ключи - имена полей, значения - данные для записи
		Fields map[string]interface{} `json:"fields"`
	} `json:"records"`
}

// DeleteRecordsRequest defines model for DeleteRecordsRequest.
type DeleteRecordsRequest struct {
	RecordIds []string `json:"recordIds"`
}

// DeleteRecordsResponse defines model for DeleteRecordsResponse.
type DeleteRecordsResponse struct {
	Message *string `json:"message,omitempty"`
	Success *bool   `json:"success,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    int     `json:"code"`
	Details *string `json:"details,omitempty"`
	Message string  `json:"message"`
}

// FieldResponse defines model for FieldResponse.
type FieldResponse struct {
	Id   string `json:"id"`
	Name string `json:"name"`
	Type string `json:"type"`
}

// Pagination defines model for Pagination.
type Pagination struct {
	HasMore  bool `json:"hasMore"`
	PageNum  int  `json:"pageNum"`
	PageSize int  `json:"pageSize"`
	Total    int  `json:"total"`
}

// RecordsResponse defines model for RecordsResponse.
type RecordsResponse struct {
	Records []TableRecord `json:"records"`
}

// SuccessResponse defines model for SuccessResponse.
type SuccessResponse struct {
	Message *string `json:"message,omitempty"`
	Success *bool   `json:"success,omitempty"`
}

// TableDataResponse defines model for TableDataResponse.
type TableDataResponse struct {
	Fields     []TableField  `json:"fields"`
	Pagination Pagination    `json:"pagination"`
	Records    []TableRecord `json:"records"`
	TableId    string        `json:"tableId"`
	TableName  *string       `json:"tableName,omitempty"`
}

// TableField defines model for TableField.
type TableField struct {
	Description *string                 `json:"description,omitempty"`
	Id          string                  `json:"id"`
	Name        string                  `json:"name"`
	Property    *map[string]interface{} `json:"property,omitempty"`
	Type        TableFieldType          `json:"type"`
}

// TableFieldType defines model for TableField.Type.
type TableFieldType string

// TableRecord defines model for TableRecord.
type TableRecord struct {
	CreatedAt *int64                 `json:"createdAt,omitempty"`
	Fields    map[string]interface{} `json:"fields"`
	RecordId  string                 `json:"recordId"`
	UpdatedAt *int64                 `json:"updatedAt,omitempty"`
}

// UpdateRecordsRequest defines model for UpdateRecordsRequest.
type UpdateRecordsRequest struct {
	Records []struct {
		Fields   map[string]interface{} `json:"fields"`
		RecordId string                 `json:"recordId"`
	} `json:"records"`
}

// PostTablesDstIdFieldsParams defines parameters for PostTablesDstIdFields.
type PostTablesDstIdFieldsParams struct {
	SpaceId string `form:"spaceId" json:"spaceId"`
}

// DeleteTablesDstIdFieldsFieldIdParams defines parameters for DeleteTablesDstIdFieldsFieldId.
type DeleteTablesDstIdFieldsFieldIdParams struct {
	SpaceId string `form:"spaceId" json:"spaceId"`
}

// GetTablesDstIdRecordsParams defines parameters for GetTablesDstIdRecords.
type GetTablesDstIdRecordsParams struct {
	ViewId   *string `form:"viewId,omitempty" json:"viewId,omitempty"`
	PageSize *int    `form:"pageSize,omitempty" json:"pageSize,omitempty"`
	PageNum  *int    `form:"pageNum,omitempty" json:"pageNum,omitempty"`
}

// PatchTablesDstIdRecordsParams defines parameters for PatchTablesDstIdRecords.
type PatchTablesDstIdRecordsParams struct {
	ViewId *string `form:"viewId,omitempty" json:"viewId,omitempty"`
}

// PostTablesDstIdRecordsParams defines parameters for PostTablesDstIdRecords.
type PostTablesDstIdRecordsParams struct {
	ViewId *string `form:"viewId,omitempty" json:"viewId,omitempty"`
}

// PatchTablesDstIdViewsViewIdFieldsFieldIdIndexJSONBody defines parameters for PatchTablesDstIdViewsViewIdFieldsFieldIdIndex.
type PatchTablesDstIdViewsViewIdFieldsFieldIdIndexJSONBody struct {
	Index int `json:"index"`
}

// PostTablesDstIdFieldsJSONRequestBody defines body for PostTablesDstIdFields for application/json ContentType.
type PostTablesDstIdFieldsJSONRequestBody = CreateFieldRequest

// DeleteTablesDstIdRecordsJSONRequestBody defines body for DeleteTablesDstIdRecords for application/json ContentType.
type DeleteTablesDstIdRecordsJSONRequestBody = DeleteRecordsRequest

// PatchTablesDstIdRecordsJSONRequestBody defines body for PatchTablesDstIdRecords for application/json ContentType.
type PatchTablesDstIdRecordsJSONRequestBody = UpdateRecordsRequest

// PostTablesDstIdRecordsJSONRequestBody defines body for PostTablesDstIdRecords for application/json ContentType.
type PostTablesDstIdRecordsJSONRequestBody = CreateRecordsRequest

// PatchTablesDstIdViewsViewIdFieldsFieldIdIndexJSONRequestBody defines body for PatchTablesDstIdViewsViewIdFieldsFieldIdIndex for application/json ContentType.
type PatchTablesDstIdViewsViewIdFieldsFieldIdIndexJSONRequestBody PatchTablesDstIdViewsViewIdFieldsFieldIdIndexJSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PostTablesDstIdFieldsWithBody request with any body
	PostTablesDstIdFieldsWithBody(ctx context.Context, dstId string, params *PostTablesDstIdFieldsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostTablesDstIdFields(ctx context.Context, dstId string, params *PostTablesDstIdFieldsParams, body PostTablesDstIdFieldsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteTablesDstIdFieldsFieldId request
	DeleteTablesDstIdFieldsFieldId(ctx context.Context, dstId string, fieldId string, params *DeleteTablesDstIdFieldsFieldIdParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteTablesDstIdRecordsWithBody request with any body
	DeleteTablesDstIdRecordsWithBody(ctx context.Context, dstId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	DeleteTablesDstIdRecords(ctx context.Context, dstId string, body DeleteTablesDstIdRecordsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetTablesDstIdRecords request
	GetTablesDstIdRecords(ctx context.Context, dstId string, params *GetTablesDstIdRecordsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PatchTablesDstIdRecordsWithBody request with any body
	PatchTablesDstIdRecordsWithBody(ctx context.Context, dstId string, params *PatchTablesDstIdRecordsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PatchTablesDstIdRecords(ctx context.Context, dstId string, params *PatchTablesDstIdRecordsParams, body PatchTablesDstIdRecordsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostTablesDstIdRecordsWithBody request with any body
	PostTablesDstIdRecordsWithBody(ctx context.Context, dstId string, params *PostTablesDstIdRecordsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostTablesDstIdRecords(ctx context.Context, dstId string, params *PostTablesDstIdRecordsParams, body PostTablesDstIdRecordsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PatchTablesDstIdViewsViewIdFieldsFieldIdIndexWithBody request with any body
	PatchTablesDstIdViewsViewIdFieldsFieldIdIndexWithBody(ctx context.Context, dstId string, viewId string, fieldId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PatchTablesDstIdViewsViewIdFieldsFieldIdIndex(ctx context.Context, dstId string, viewId string, fieldId string, body PatchTablesDstIdViewsViewIdFieldsFieldIdIndexJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PostTablesDstIdFieldsWithBody(ctx context.Context, dstId string, params *PostTablesDstIdFieldsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostTablesDstIdFieldsRequestWithBody(c.Server, dstId, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostTablesDstIdFields(ctx context.Context, dstId string, params *PostTablesDstIdFieldsParams, body PostTablesDstIdFieldsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostTablesDstIdFieldsRequest(c.Server, dstId, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteTablesDstIdFieldsFieldId(ctx context.Context, dstId string, fieldId string, params *DeleteTablesDstIdFieldsFieldIdParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteTablesDstIdFieldsFieldIdRequest(c.Server, dstId, fieldId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteTablesDstIdRecordsWithBody(ctx context.Context, dstId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteTablesDstIdRecordsRequestWithBody(c.Server, dstId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteTablesDstIdRecords(ctx context.Context, dstId string, body DeleteTablesDstIdRecordsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteTablesDstIdRecordsRequest(c.Server, dstId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetTablesDstIdRecords(ctx context.Context, dstId string, params *GetTablesDstIdRecordsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetTablesDstIdRecordsRequest(c.Server, dstId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PatchTablesDstIdRecordsWithBody(ctx context.Context, dstId string, params *PatchTablesDstIdRecordsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchTablesDstIdRecordsRequestWithBody(c.Server, dstId, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PatchTablesDstIdRecords(ctx context.Context, dstId string, params *PatchTablesDstIdRecordsParams, body PatchTablesDstIdRecordsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchTablesDstIdRecordsRequest(c.Server, dstId, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostTablesDstIdRecordsWithBody(ctx context.Context, dstId string, params *PostTablesDstIdRecordsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostTablesDstIdRecordsRequestWithBody(c.Server, dstId, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostTablesDstIdRecords(ctx context.Context, dstId string, params *PostTablesDstIdRecordsParams, body PostTablesDstIdRecordsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostTablesDstIdRecordsRequest(c.Server, dstId, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PatchTablesDstIdViewsViewIdFieldsFieldIdIndexWithBody(ctx context.Context, dstId string, viewId string, fieldId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchTablesDstIdViewsViewIdFieldsFieldIdIndexRequestWithBody(c.Server, dstId, viewId, fieldId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PatchTablesDstIdViewsViewIdFieldsFieldIdIndex(ctx context.Context, dstId string, viewId string, fieldId string, body PatchTablesDstIdViewsViewIdFieldsFieldIdIndexJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchTablesDstIdViewsViewIdFieldsFieldIdIndexRequest(c.Server, dstId, viewId, fieldId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPostTablesDstIdFieldsRequest calls the generic PostTablesDstIdFields builder with application/json body
func NewPostTablesDstIdFieldsRequest(server string, dstId string, params *PostTablesDstIdFieldsParams, body PostTablesDstIdFieldsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostTablesDstIdFieldsRequestWithBody(server, dstId, params, "application/json", bodyReader)
}

// NewPostTablesDstIdFieldsRequestWithBody generates requests for PostTablesDstIdFields with any type of body
func NewPostTablesDstIdFieldsRequestWithBody(server string, dstId string, params *PostTablesDstIdFieldsParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "dstId", dstId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/tables/%s/fields", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "spaceId", params.SpaceId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteTablesDstIdFieldsFieldIdRequest generates requests for DeleteTablesDstIdFieldsFieldId
func NewDeleteTablesDstIdFieldsFieldIdRequest(server string, dstId string, fieldId string, params *DeleteTablesDstIdFieldsFieldIdParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "dstId", dstId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "fieldId", fieldId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/tables/%s/fields/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "spaceId", params.SpaceId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDeleteTablesDstIdRecordsRequest calls the generic DeleteTablesDstIdRecords builder with application/json body
func NewDeleteTablesDstIdRecordsRequest(server string, dstId string, body DeleteTablesDstIdRecordsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewDeleteTablesDstIdRecordsRequestWithBody(server, dstId, "application/json", bodyReader)
}

// NewDeleteTablesDstIdRecordsRequestWithBody generates requests for DeleteTablesDstIdRecords with any type of body
func NewDeleteTablesDstIdRecordsRequestWithBody(server string, dstId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "dstId", dstId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/tables/%s/records", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetTablesDstIdRecordsRequest generates requests for GetTablesDstIdRecords
func NewGetTablesDstIdRecordsRequest(server string, dstId string, params *GetTablesDstIdRecordsParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "dstId", dstId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/tables/%s/records", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.ViewId != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "viewId", *params.ViewId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.PageSize != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "pageSize", *params.PageSize, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.PageNum != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "pageNum", *params.PageNum, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPatchTablesDstIdRecordsRequest calls the generic PatchTablesDstIdRecords builder with application/json body
func NewPatchTablesDstIdRecordsRequest(server string, dstId string, params *PatchTablesDstIdRecordsParams, body PatchTablesDstIdRecordsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPatchTablesDstIdRecordsRequestWithBody(server, dstId, params, "application/json", bodyReader)
}

// NewPatchTablesDstIdRecordsRequestWithBody generates requests for PatchTablesDstIdRecords with any type of body
func NewPatchTablesDstIdRecordsRequestWithBody(server string, dstId string, params *PatchTablesDstIdRecordsParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "dstId", dstId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/tables/%s/records", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.ViewId != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "viewId", *params.ViewId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("PATCH", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostTablesDstIdRecordsRequest calls the generic PostTablesDstIdRecords builder with application/json body
func NewPostTablesDstIdRecordsRequest(server string, dstId string, params *PostTablesDstIdRecordsParams, body PostTablesDstIdRecordsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostTablesDstIdRecordsRequestWithBody(server, dstId, params, "application/json", bodyReader)
}

// NewPostTablesDstIdRecordsRequestWithBody generates requests for PostTablesDstIdRecords with any type of body
func NewPostTablesDstIdRecordsRequestWithBody(server string, dstId string, params *PostTablesDstIdRecordsParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "dstId", dstId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/tables/%s/records", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.ViewId != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "viewId", *params.ViewId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPatchTablesDstIdViewsViewIdFieldsFieldIdIndexRequest calls the generic PatchTablesDstIdViewsViewIdFieldsFieldIdIndex builder with application/json body
func NewPatchTablesDstIdViewsViewIdFieldsFieldIdIndexRequest(server string, dstId string, viewId string, fieldId string, body PatchTablesDstIdViewsViewIdFieldsFieldIdIndexJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPatchTablesDstIdViewsViewIdFieldsFieldIdIndexRequestWithBody(server, dstId, viewId, fieldId, "application/json", bodyReader)
}

// NewPatchTablesDstIdViewsViewIdFieldsFieldIdIndexRequestWithBody generates requests for PatchTablesDstIdViewsViewIdFieldsFieldIdIndex with any type of body
func NewPatchTablesDstIdViewsViewIdFieldsFieldIdIndexRequestWithBody(server string, dstId string, viewId string, fieldId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "dstId", dstId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "viewId", viewId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithOptions("simple", false, "fieldId", fieldId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/tables/%s/views/%s/fields/%s/index", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PATCH", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PostTablesDstIdFieldsWithBodyWithResponse request with any body
	PostTablesDstIdFieldsWithBodyWithResponse(ctx context.Context, dstId string, params *PostTablesDstIdFieldsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostTablesDstIdFieldsResponse, error)

	PostTablesDstIdFieldsWithResponse(ctx context.Context, dstId string, params *PostTablesDstIdFieldsParams, body PostTablesDstIdFieldsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostTablesDstIdFieldsResponse, error)

	// DeleteTablesDstIdFieldsFieldIdWithResponse request
	DeleteTablesDstIdFieldsFieldIdWithResponse(ctx context.Context, dstId string, fieldId string, params *DeleteTablesDstIdFieldsFieldIdParams, reqEditors ...RequestEditorFn) (*DeleteTablesDstIdFieldsFieldIdResponse, error)

	// DeleteTablesDstIdRecordsWithBodyWithResponse request with any body
	DeleteTablesDstIdRecordsWithBodyWithResponse(ctx context.Context, dstId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*DeleteTablesDstIdRecordsResponse, error)

	DeleteTablesDstIdRecordsWithResponse(ctx context.Context, dstId string, body DeleteTablesDstIdRecordsJSONRequestBody, reqEditors ...RequestEditorFn) (*DeleteTablesDstIdRecordsResponse, error)

	// GetTablesDstIdRecordsWithResponse request
	GetTablesDstIdRecordsWithResponse(ctx context.Context, dstId string, params *GetTablesDstIdRecordsParams, reqEditors ...RequestEditorFn) (*GetTablesDstIdRecordsResponse, error)

	// PatchTablesDstIdRecordsWithBodyWithResponse request with any body
	PatchTablesDstIdRecordsWithBodyWithResponse(ctx context.Context, dstId string, params *PatchTablesDstIdRecordsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PatchTablesDstIdRecordsResponse, error)

	PatchTablesDstIdRecordsWithResponse(ctx context.Context, dstId string, params *PatchTablesDstIdRecordsParams, body PatchTablesDstIdRecordsJSONRequestBody, reqEditors ...RequestEditorFn) (*PatchTablesDstIdRecordsResponse, error)

	// PostTablesDstIdRecordsWithBodyWithResponse request with any body
	PostTablesDstIdRecordsWithBodyWithResponse(ctx context.Context, dstId string, params *PostTablesDstIdRecordsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostTablesDstIdRecordsResponse, error)

	PostTablesDstIdRecordsWithResponse(ctx context.Context, dstId string, params *PostTablesDstIdRecordsParams, body PostTablesDstIdRecordsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostTablesDstIdRecordsResponse, error)

	// PatchTablesDstIdViewsViewIdFieldsFieldIdIndexWithBodyWithResponse request with any body
	PatchTablesDstIdViewsViewIdFieldsFieldIdIndexWithBodyWithResponse(ctx context.Context, dstId string, viewId string, fieldId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PatchTablesDstIdViewsViewIdFieldsFieldIdIndexResponse, error)

	PatchTablesDstIdViewsViewIdFieldsFieldIdIndexWithResponse(ctx context.Context, dstId string, viewId string, fieldId string, body PatchTablesDstIdViewsViewIdFieldsFieldIdIndexJSONRequestBody, reqEditors ...RequestEditorFn) (*PatchTablesDstIdViewsViewIdFieldsFieldIdIndexResponse, error)
}

type PostTablesDstIdFieldsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *FieldResponse
	JSON400      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostTablesDstIdFieldsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostTablesDstIdFieldsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteTablesDstIdFieldsFieldIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *SuccessResponse
	JSON400      *ErrorResponse
	JSON404      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r DeleteTablesDstIdFieldsFieldIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteTablesDstIdFieldsFieldIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteTablesDstIdRecordsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *DeleteRecordsResponse
	JSON400      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r DeleteTablesDstIdRecordsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteTablesDstIdRecordsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetTablesDstIdRecordsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *TableDataResponse
	JSON400      *ErrorResponse
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetTablesDstIdRecordsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetTablesDstIdRecordsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PatchTablesDstIdRecordsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RecordsResponse
	JSON400      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PatchTablesDstIdRecordsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PatchTablesDstIdRecordsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostTablesDstIdRecordsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *RecordsResponse
	JSON400      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostTablesDstIdRecordsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostTablesDstIdRecordsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PatchTablesDstIdViewsViewIdFieldsFieldIdIndexResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *SuccessResponse
	JSON400      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PatchTablesDstIdViewsViewIdFieldsFieldIdIndexResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PatchTablesDstIdViewsViewIdFieldsFieldIdIndexResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// PostTablesDstIdFieldsWithBodyWithResponse request with arbitrary body returning *PostTablesDstIdFieldsResponse
func (c *ClientWithResponses) PostTablesDstIdFieldsWithBodyWithResponse(ctx context.Context, dstId string, params *PostTablesDstIdFieldsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostTablesDstIdFieldsResponse, error) {
	rsp, err := c.PostTablesDstIdFieldsWithBody(ctx, dstId, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostTablesDstIdFieldsResponse(rsp)
}

func (c *ClientWithResponses) PostTablesDstIdFieldsWithResponse(ctx context.Context, dstId string, params *PostTablesDstIdFieldsParams, body PostTablesDstIdFieldsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostTablesDstIdFieldsResponse, error) {
	rsp, err := c.PostTablesDstIdFields(ctx, dstId, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostTablesDstIdFieldsResponse(rsp)
}

// DeleteTablesDstIdFieldsFieldIdWithResponse request returning *DeleteTablesDstIdFieldsFieldIdResponse
func (c *ClientWithResponses) DeleteTablesDstIdFieldsFieldIdWithResponse(ctx context.Context, dstId string, fieldId string, params *DeleteTablesDstIdFieldsFieldIdParams, reqEditors ...RequestEditorFn) (*DeleteTablesDstIdFieldsFieldIdResponse, error) {
	rsp, err := c.DeleteTablesDstIdFieldsFieldId(ctx, dstId, fieldId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteTablesDstIdFieldsFieldIdResponse(rsp)
}

// DeleteTablesDstIdRecordsWithBodyWithResponse request with arbitrary body returning *DeleteTablesDstIdRecordsResponse
func (c *ClientWithResponses) DeleteTablesDstIdRecordsWithBodyWithResponse(ctx context.Context, dstId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*DeleteTablesDstIdRecordsResponse, error) {
	rsp, err := c.DeleteTablesDstIdRecordsWithBody(ctx, dstId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteTablesDstIdRecordsResponse(rsp)
}

func (c *ClientWithResponses) DeleteTablesDstIdRecordsWithResponse(ctx context.Context, dstId string, body DeleteTablesDstIdRecordsJSONRequestBody, reqEditors ...RequestEditorFn) (*DeleteTablesDstIdRecordsResponse, error) {
	rsp, err := c.DeleteTablesDstIdRecords(ctx, dstId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteTablesDstIdRecordsResponse(rsp)
}

// GetTablesDstIdRecordsWithResponse request returning *GetTablesDstIdRecordsResponse
func (c *ClientWithResponses) GetTablesDstIdRecordsWithResponse(ctx context.Context, dstId string, params *GetTablesDstIdRecordsParams, reqEditors ...RequestEditorFn) (*GetTablesDstIdRecordsResponse, error) {
	rsp, err := c.GetTablesDstIdRecords(ctx, dstId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetTablesDstIdRecordsResponse(rsp)
}

// PatchTablesDstIdRecordsWithBodyWithResponse request with arbitrary body returning *PatchTablesDstIdRecordsResponse
func (c *ClientWithResponses) PatchTablesDstIdRecordsWithBodyWithResponse(ctx context.Context, dstId string, params *PatchTablesDstIdRecordsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PatchTablesDstIdRecordsResponse, error) {
	rsp, err := c.PatchTablesDstIdRecordsWithBody(ctx, dstId, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePatchTablesDstIdRecordsResponse(rsp)
}

func (c *ClientWithResponses) PatchTablesDstIdRecordsWithResponse(ctx context.Context, dstId string, params *PatchTablesDstIdRecordsParams, body PatchTablesDstIdRecordsJSONRequestBody, reqEditors ...RequestEditorFn) (*PatchTablesDstIdRecordsResponse, error) {
	rsp, err := c.PatchTablesDstIdRecords(ctx, dstId, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePatchTablesDstIdRecordsResponse(rsp)
}

// PostTablesDstIdRecordsWithBodyWithResponse request with arbitrary body returning *PostTablesDstIdRecordsResponse
func (c *ClientWithResponses) PostTablesDstIdRecordsWithBodyWithResponse(ctx context.Context, dstId string, params *PostTablesDstIdRecordsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostTablesDstIdRecordsResponse, error) {
	rsp, err := c.PostTablesDstIdRecordsWithBody(ctx, dstId, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostTablesDstIdRecordsResponse(rsp)
}

func (c *ClientWithResponses) PostTablesDstIdRecordsWithResponse(ctx context.Context, dstId string, params *PostTablesDstIdRecordsParams, body PostTablesDstIdRecordsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostTablesDstIdRecordsResponse, error) {
	rsp, err := c.PostTablesDstIdRecords(ctx, dstId, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostTablesDstIdRecordsResponse(rsp)
}

// PatchTablesDstIdViewsViewIdFieldsFieldIdIndexWithBodyWithResponse request with arbitrary body returning *PatchTablesDstIdViewsViewIdFieldsFieldIdIndexResponse
func (c *ClientWithResponses) PatchTablesDstIdViewsViewIdFieldsFieldIdIndexWithBodyWithResponse(ctx context.Context, dstId string, viewId string, fieldId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PatchTablesDstIdViewsViewIdFieldsFieldIdIndexResponse, error) {
	rsp, err := c.PatchTablesDstIdViewsViewIdFieldsFieldIdIndexWithBody(ctx, dstId, viewId, fieldId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePatchTablesDstIdViewsViewIdFieldsFieldIdIndexResponse(rsp)
}

func (c *ClientWithResponses) PatchTablesDstIdViewsViewIdFieldsFieldIdIndexWithResponse(ctx context.Context, dstId string, viewId string, fieldId string, body PatchTablesDstIdViewsViewIdFieldsFieldIdIndexJSONRequestBody, reqEditors ...RequestEditorFn) (*PatchTablesDstIdViewsViewIdFieldsFieldIdIndexResponse, error) {
	rsp, err := c.PatchTablesDstIdViewsViewIdFieldsFieldIdIndex(ctx, dstId, viewId, fieldId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePatchTablesDstIdViewsViewIdFieldsFieldIdIndexResponse(rsp)
}

// ParsePostTablesDstIdFieldsResponse parses an HTTP response from a PostTablesDstIdFieldsWithResponse call
func ParsePostTablesDstIdFieldsResponse(rsp *http.Response) (*PostTablesDstIdFieldsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostTablesDstIdFieldsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest FieldResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// ParseDeleteTablesDstIdFieldsFieldIdResponse parses an HTTP response from a DeleteTablesDstIdFieldsFieldIdWithResponse call
func ParseDeleteTablesDstIdFieldsFieldIdResponse(rsp *http.Response) (*DeleteTablesDstIdFieldsFieldIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteTablesDstIdFieldsFieldIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SuccessResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseDeleteTablesDstIdRecordsResponse parses an HTTP response from a DeleteTablesDstIdRecordsWithResponse call
func ParseDeleteTablesDstIdRecordsResponse(rsp *http.Response) (*DeleteTablesDstIdRecordsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteTablesDstIdRecordsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DeleteRecordsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetTablesDstIdRecordsResponse parses an HTTP response from a GetTablesDstIdRecordsWithResponse call
func ParseGetTablesDstIdRecordsResponse(rsp *http.Response) (*GetTablesDstIdRecordsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetTablesDstIdRecordsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TableDataResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePatchTablesDstIdRecordsResponse parses an HTTP response from a PatchTablesDstIdRecordsWithResponse call
func ParsePatchTablesDstIdRecordsResponse(rsp *http.Response) (*PatchTablesDstIdRecordsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PatchTablesDstIdRecordsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RecordsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostTablesDstIdRecordsResponse parses an HTTP response from a PostTablesDstIdRecordsWithResponse call
func ParsePostTablesDstIdRecordsResponse(rsp *http.Response) (*PostTablesDstIdRecordsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostTablesDstIdRecordsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest RecordsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePatchTablesDstIdViewsViewIdFieldsFieldIdIndexResponse parses an HTTP response from a PatchTablesDstIdViewsViewIdFieldsFieldIdIndexWithResponse call
func ParsePatchTablesDstIdViewsViewIdFieldsFieldIdIndexResponse(rsp *http.Response) (*PatchTablesDstIdViewsViewIdFieldsFieldIdIndexResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PatchTablesDstIdViewsViewIdFieldsFieldIdIndexResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SuccessResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}
