// Package authhttp provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package authhttp

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for CheckPermissionRequestAction.
const (
	Delete CheckPermissionRequestAction = "delete"
	Read   CheckPermissionRequestAction = "read"
	Write  CheckPermissionRequestAction = "write"
)

// Valid indicates whether the value is a known member of the CheckPermissionRequestAction enum.
func (e CheckPermissionRequestAction) Valid() bool {
	switch e {
	case Delete:
		return true
	case Read:
		return true
	case Write:
		return true
	default:
		return false
	}
}

// Defines values for CheckPermissionRequestResource.
const (
	Document CheckPermissionRequestResource = "document"
	Field    CheckPermissionRequestResource = "field"
	Table    CheckPermissionRequestResource = "table"
)

// Valid indicates whether the value is a known member of the CheckPermissionRequestResource enum.
func (e CheckPermissionRequestResource) Valid() bool {
	switch e {
	case Document:
		return true
	case Field:
		return true
	case Table:
		return true
	default:
		return false
	}
}

// Defines values for UpdateRoleRequestRole.
const (
	UpdateRoleRequestRoleAdmin  UpdateRoleRequestRole = "admin"
	UpdateRoleRequestRoleEditor UpdateRoleRequestRole = "editor"
	UpdateRoleRequestRoleReader UpdateRoleRequestRole = "reader"
)

// Valid indicates whether the value is a known member of the UpdateRoleRequestRole enum.
func (e UpdateRoleRequestRole) Valid() bool {
	switch e {
	case UpdateRoleRequestRoleAdmin:
		return true
	case UpdateRoleRequestRoleEditor:
		return true
	case UpdateRoleRequestRoleReader:
		return true
	default:
		return false
	}
}

// Defines values for UserResponseRole.
const (
	UserResponseRoleAdmin  UserResponseRole = "admin"
	UserResponseRoleEditor UserResponseRole = "editor"
	UserResponseRoleReader UserResponseRole = "reader"
)

// Valid indicates whether the value is a known member of the UserResponseRole enum.
func (e UserResponseRole) Valid() bool {
	switch e {
	case UserResponseRoleAdmin:
		return true
	case UserResponseRoleEditor:
		return true
	case UserResponseRoleReader:
		return true
	default:
		return false
	}
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	AccessToken  *string       `json:"accessToken,omitempty"`
	RefreshToken *string       `json:"refreshToken,omitempty"`
	User         *UserResponse `json:"user,omitempty"`
}

// CheckPermissionRequest defines model for CheckPermissionRequest.
type CheckPermissionRequest struct {
	Action   CheckPermissionRequestAction   `json:"action"`
	Resource CheckPermissionRequestResource `json:"resource"`
}

// CheckPermissionRequestAction defines model for CheckPermissionRequest.Action.
type CheckPermissionRequestAction string

// CheckPermissionRequestResource defines model for CheckPermissionRequest.Resource.
type CheckPermissionRequestResource string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    *int    `json:"code,omitempty"`
	Details *string `json:"details,omitempty"`
	Message *string `json:"message,omitempty"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// PermissionResponse defines model for PermissionResponse.
type PermissionResponse struct {
	Allowed *bool `json:"allowed,omitempty"`
}

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	RefreshToken string `json:"refreshToken"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email    openapi_types.Email `json:"email"`
	Name     string              `json:"name"`
	Password string              `json:"password"`
}

// SuccessResponse defines model for SuccessResponse.
type SuccessResponse struct {
	Message *string `json:"message,omitempty"`
	Success *bool   `json:"success,omitempty"`
}

// UpdateRoleRequest defines model for UpdateRoleRequest.
type UpdateRoleRequest struct {
	Role UpdateRoleRequestRole `json:"role"`
}

// UpdateRoleRequestRole defines model for UpdateRoleRequest.Role.
type UpdateRoleRequestRole string

// UserResponse defines model for UserResponse.
type UserResponse struct {
	CreatedAt *time.Time        `json:"createdAt,omitempty"`
	Email     *string           `json:"email,omitempty"`
	Id        *string           `json:"id,omitempty"`
	Name      *string           `json:"name,omitempty"`
	Role      *UserResponseRole `json:"role,omitempty"`
}

// UserResponseRole defines model for UserResponse.Role.
type UserResponseRole string

// PostAuthCheckPermissionJSONRequestBody defines body for PostAuthCheckPermission for application/json ContentType.
type PostAuthCheckPermissionJSONRequestBody = CheckPermissionRequest

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody = LoginRequest

// PostAuthRefreshJSONRequestBody defines body for PostAuthRefresh for application/json ContentType.
type PostAuthRefreshJSONRequestBody = RefreshRequest

// PostAuthRegisterJSONRequestBody defines body for PostAuthRegister for application/json ContentType.
type PostAuthRegisterJSONRequestBody = RegisterRequest

// PatchUsersUserIdRoleJSONRequestBody defines body for PatchUsersUserIdRole for application/json ContentType.
type PatchUsersUserIdRoleJSONRequestBody = UpdateRoleRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Проверить права доступа (для внутренних сервисов)
	// (POST /auth/check-permission)
	PostAuthCheckPermission(c *gin.Context)
	// Вход в систему
	// (POST /auth/login)
	PostAuthLogin(c *gin.Context)
	// Выход из системы
	// (POST /auth/logout)
	PostAuthLogout(c *gin.Context)
	// Получить информацию о текущем пользователе
	// (GET /auth/me)
	GetAuthMe(c *gin.Context)
	// Обновление токена
	// (POST /auth/refresh)
	PostAuthRefresh(c *gin.Context)
	// Регистрация нового пользователя
	// (POST /auth/register)
	PostAuthRegister(c *gin.Context)
	// Список пользователей (только для admin)
	// (GET /users)
	GetUsers(c *gin.Context)
	// Изменить роль пользователя (только для admin)
	// (PATCH /users/{userId}/role)
	PatchUsersUserIdRole(c *gin.Context, userId string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// PostAuthCheckPermission operation middleware
func (siw *ServerInterfaceWrapper) PostAuthCheckPermission(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostAuthCheckPermission(c)
}

// PostAuthLogin operation middleware
func (siw *ServerInterfaceWrapper) PostAuthLogin(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostAuthLogin(c)
}

// PostAuthLogout operation middleware
func (siw *ServerInterfaceWrapper) PostAuthLogout(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostAuthLogout(c)
}

// GetAuthMe operation middleware
func (siw *ServerInterfaceWrapper) GetAuthMe(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAuthMe(c)
}

// PostAuthRefresh operation middleware
func (siw *ServerInterfaceWrapper) PostAuthRefresh(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostAuthRefresh(c)
}

// PostAuthRegister operation middleware
func (siw *ServerInterfaceWrapper) PostAuthRegister(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostAuthRegister(c)
}

// GetUsers operation middleware
func (siw *ServerInterfaceWrapper) GetUsers(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetUsers(c)
}

// PatchUsersUserIdRole operation middleware
func (siw *ServerInterfaceWrapper) PatchUsersUserIdRole(c *gin.Context) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "userId", c.Param("userId"), &userId, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PatchUsersUserIdRole(c, userId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/auth/check-permission", wrapper.PostAuthCheckPermission)
	router.POST(options.BaseURL+"/auth/login", wrapper.PostAuthLogin)
	router.POST(options.BaseURL+"/auth/logout", wrapper.PostAuthLogout)
	router.GET(options.BaseURL+"/auth/me", wrapper.GetAuthMe)
	router.POST(options.BaseURL+"/auth/refresh", wrapper.PostAuthRefresh)
	router.POST(options.BaseURL+"/auth/register", wrapper.PostAuthRegister)
	router.GET(options.BaseURL+"/users", wrapper.GetUsers)
	router.PATCH(options.BaseURL+"/users/:userId/role", wrapper.PatchUsersUserIdRole)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xYX28Txxb/KqvhPnClDU4uV1e6foOqraiohAJRHxJLbHZP7IXdnWVmNiiKLCUxlFag",
	"IqE+8NIC7RdwTdyYEDtf4cw3qs7MOvE6u4kjSFoJkd2dmTPnnN/v/PMm83mc8gQSJVl9k0m/BbFnHm9k",
	"qrUIMuWJBHpPBU9BqBDMquf7IOU9/hASelUbKbA6k0qESZO1XSZgTYBsVW/IJAha+JeANVZnV2rHitRy",
	"LWpLEsSRCu22O5bCVx+Ar0jKFy3wH94BEYdShjxZhEcZSFWmrgq5UQSSLGb1ZSbAC5jLHotQAXNZABEo",
	"YA23zBTJM+HD5OmA+1kMiWIuU95qRBLWQoiCEgFGwqMsFBDYe3Np7lipRoldXwrBRbX3fR7AhFfDREET",
	"BB0MQHlhJEtdHoOUXhNK1spce5s3w2qHQuyFET2scRF7itXzLyX+Sz0pH3MRlN876ZuxiKMTZa6ZRLuS",
	"nVHEH8PkjaucR+Al5aYuWrJWGnsGmU8gPLG7UXpdM5SKqP3pzk28GErBnvR6HCa3IWmqFqv/zz0vBvkd",
	"ZYbczUwWqMahmnEuk/bwrBgtpYGnYJFHUA0Tj2A6xEEwl0EQKk4PXhCHyQwxSoLKDC4kpJNRKcBTENxQ",
	"BehI7TkVxlAG3xHSJ1bCoPRzJd6fZPyUoYQO+JkI1cZdSsXWvJvgCRBUFuht1bx9Nbbym+/uMdeWDwOl",
	"WT22uKVUytokOEzWOJ0PQPoiTG1aZvgO+3oLezjQ2w52dUfvYB+HegcH+gkOcB+7+nsc4MChf13s6R0c",
	"6S0c4N545dpKspJcueLgWxzhR9p2SA/6Be7hCHvYNSI/Yh8/rCRzzn3roPvOnEOyzMZ9HDn6mb0aB9h3",
	"cBdHuK87eJBrM8KeOWydag5vYR93sYv7Rtkte9dZ5w0WdNwqiUP9HD+Y7Xpb7+gOHroO/a+3yFijdS6x",
	"1Cj9Eg9wsJKQw0NFRDDl27kLYj30wblx5xZz2ToIad29cG3+2jyxhqeQeGnI6uy6+URxr1oG7pqXqVbN",
	"pwI7lx7lXMN6bqOPuO8RgLcCVmd3uFR06VRJZja0QKqbPNiwxStRVDopT6dpFPpGRu2BtNJt8T+rNago",
	"/O1iKCuRga3gJmSNXf+Zn/9sWpTUIqPBFLnfYh/3dIdw0zuEmWOQJQCJ9fs4KMQcqy8Xo2250W5Qwoxj",
	"T2yQwDcTpwd6R79wjqjSLbAIu85V3CWCONjDIcWVIeyQ6KSfOnr7OO5I4r9NQ9OUlEGoqxCJF7EGKWfp",
	"EFFTcDYHTO9wQcgX+pJLxrvQE5ch/bvexkPs6x/GEd3TT3GEuxRr/51f+GyKFPvDMk1+wX5OENKk7+iO",
	"foZ9vZO/mpQ1tC+WfMfsemV1drBH/BgQl7CPB7ozQQ5iwxQxeKZmYgbtu0CMppuSGWF6PgbqXIH4anzO",
	"oVJUdNfzU9xli3gTSjz1NRhHfQsX6aSpyeqkh17jUD8xJfbAFljKIKPKmnre/GWkECPz7DU4cd1PdJ0R",
	"v687+kfyaPXt1Y7Om/GziZnPABeUtKYmjH9a2vqN2hQqCw6O8A8cGveapmM6N/xaXDY9ielrzHHsngqF",
	"HXtmwSLfeVFgFOevmdBYuDw03pS2eC8cU6L3bOa2BWX+bywoxQpC2vz/ErWp9FEH/yRKbtukYZJxT3eo",
	"8k1Tmbqy9zZfU+80TnKW3SN8X5nu9MtylmcShDwtry+ZDZ8Y6KGCWJ4vvx+NYZ4Q3kapP9/hYd4D7p8y",
	"OFmcr5fMbz8f95wOzWSmH+2bvD08Z3GYTRXnamFsy5tcM1dNNrEWkwl8apv051bQro0n5tRTfqskGdFn",
	"g9iSObDIzc98qSe8GJRBenmTUTdsZqbx7yR1ZuWz6ZTiTmA4PYE3LibRnfzN5JILz5ltxlsL4Ymyg91L",
	"odpr3LOjed6HmLHK6FMR+OdlndFGrI/ZkomI1VnNS8Pa+gJrN9p/BQAA//9cCAUYgBcAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
