// Package tableshttp provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package tableshttp

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// Defines values for TableFieldType.
const (
	Attachment   TableFieldType = "Attachment"
	Checkbox     TableFieldType = "Checkbox"
	Currency     TableFieldType = "Currency"
	DateTime     TableFieldType = "DateTime"
	Email        TableFieldType = "Email"
	Member       TableFieldType = "Member"
	MultiSelect  TableFieldType = "MultiSelect"
	Number       TableFieldType = "Number"
	Percent      TableFieldType = "Percent"
	Phone        TableFieldType = "Phone"
	Rating       TableFieldType = "Rating"
	SingleSelect TableFieldType = "SingleSelect"
	SingleText   TableFieldType = "SingleText"
	Text         TableFieldType = "Text"
	URL          TableFieldType = "URL"
)

// Valid indicates whether the value is a known member of the TableFieldType enum.
func (e TableFieldType) Valid() bool {
	switch e {
	case Attachment:
		return true
	case Checkbox:
		return true
	case Currency:
		return true
	case DateTime:
		return true
	case Email:
		return true
	case Member:
		return true
	case MultiSelect:
		return true
	case Number:
		return true
	case Percent:
		return true
	case Phone:
		return true
	case Rating:
		return true
	case SingleSelect:
		return true
	case SingleText:
		return true
	case Text:
		return true
	case URL:
		return true
	default:
		return false
	}
}

// CreateRecordsRequest defines model for CreateRecordsRequest.
type CreateRecordsRequest struct {
	Records []struct {
		// Fields Ключи - имена полей, значения - данные для записи
		Fields map[string]interface{} `json:"fields"`
	} `json:"records"`
}

// DeleteRecordsRequest defines model for DeleteRecordsRequest.
type DeleteRecordsRequest struct {
	RecordIds []string `json:"recordIds"`
}

// DeleteRecordsResponse defines model for DeleteRecordsResponse.
type DeleteRecordsResponse struct {
	Message *string `json:"message,omitempty"`
	Success *bool   `json:"success,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    int     `json:"code"`
	Details *string `json:"details,omitempty"`
	Message string  `json:"message"`
}

// Pagination defines model for Pagination.
type Pagination struct {
	HasMore  bool `json:"hasMore"`
	PageNum  int  `json:"pageNum"`
	PageSize int  `json:"pageSize"`
	Total    int  `json:"total"`
}

// RecordsResponse defines model for RecordsResponse.
type RecordsResponse struct {
	Records []TableRecord `json:"records"`
}

// TableDataResponse defines model for TableDataResponse.
type TableDataResponse struct {
	Fields     []TableField  `json:"fields"`
	Pagination Pagination    `json:"pagination"`
	Records    []TableRecord `json:"records"`
	TableId    string        `json:"tableId"`
	TableName  *string       `json:"tableName,omitempty"`
}

// TableField defines model for TableField.
type TableField struct {
	Description *string                 `json:"description,omitempty"`
	Id          string                  `json:"id"`
	Name        string                  `json:"name"`
	Property    *map[string]interface{} `json:"property,omitempty"`
	Type        TableFieldType          `json:"type"`
}

// TableFieldType defines model for TableField.Type.
type TableFieldType string

// TableRecord defines model for TableRecord.
type TableRecord struct {
	CreatedAt *int64                 `json:"createdAt,omitempty"`
	Fields    map[string]interface{} `json:"fields"`
	RecordId  string                 `json:"recordId"`
	UpdatedAt *int64                 `json:"updatedAt,omitempty"`
}

// UpdateRecordsRequest defines model for UpdateRecordsRequest.
type UpdateRecordsRequest struct {
	Records []struct {
		Fields   map[string]interface{} `json:"fields"`
		RecordId string                 `json:"recordId"`
	} `json:"records"`
}

// GetTablesDstIdRecordsParams defines parameters for GetTablesDstIdRecords.
type GetTablesDstIdRecordsParams struct {
	ViewId   *string `form:"viewId,omitempty" json:"viewId,omitempty"`
	PageSize *int    `form:"pageSize,omitempty" json:"pageSize,omitempty"`
	PageNum  *int    `form:"pageNum,omitempty" json:"pageNum,omitempty"`
}

// PatchTablesDstIdRecordsParams defines parameters for PatchTablesDstIdRecords.
type PatchTablesDstIdRecordsParams struct {
	ViewId *string `form:"viewId,omitempty" json:"viewId,omitempty"`
}

// PostTablesDstIdRecordsParams defines parameters for PostTablesDstIdRecords.
type PostTablesDstIdRecordsParams struct {
	ViewId *string `form:"viewId,omitempty" json:"viewId,omitempty"`
}

// DeleteTablesDstIdRecordsJSONRequestBody defines body for DeleteTablesDstIdRecords for application/json ContentType.
type DeleteTablesDstIdRecordsJSONRequestBody = DeleteRecordsRequest

// PatchTablesDstIdRecordsJSONRequestBody defines body for PatchTablesDstIdRecords for application/json ContentType.
type PatchTablesDstIdRecordsJSONRequestBody = UpdateRecordsRequest

// PostTablesDstIdRecordsJSONRequestBody defines body for PostTablesDstIdRecords for application/json ContentType.
type PostTablesDstIdRecordsJSONRequestBody = CreateRecordsRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Удалить записи из таблицы
	// (DELETE /tables/{dstId}/records)
	DeleteTablesDstIdRecords(c *gin.Context, dstId string)
	// Получить записи таблицы
	// (GET /tables/{dstId}/records)
	GetTablesDstIdRecords(c *gin.Context, dstId string, params GetTablesDstIdRecordsParams)
	// Обновить записи в таблице
	// (PATCH /tables/{dstId}/records)
	PatchTablesDstIdRecords(c *gin.Context, dstId string, params PatchTablesDstIdRecordsParams)
	// Создать записи в таблице
	// (POST /tables/{dstId}/records)
	PostTablesDstIdRecords(c *gin.Context, dstId string, params PostTablesDstIdRecordsParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// DeleteTablesDstIdRecords operation middleware
func (siw *ServerInterfaceWrapper) DeleteTablesDstIdRecords(c *gin.Context) {

	var err error

	// ------------- Path parameter "dstId" -------------
	var dstId string

	err = runtime.BindStyledParameterWithOptions("simple", "dstId", c.Param("dstId"), &dstId, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter dstId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteTablesDstIdRecords(c, dstId)
}

// GetTablesDstIdRecords operation middleware
func (siw *ServerInterfaceWrapper) GetTablesDstIdRecords(c *gin.Context) {

	var err error

	// ------------- Path parameter "dstId" -------------
	var dstId string

	err = runtime.BindStyledParameterWithOptions("simple", "dstId", c.Param("dstId"), &dstId, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter dstId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTablesDstIdRecordsParams

	// ------------- Optional query parameter "viewId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "viewId", c.Request.URL.Query(), &params.ViewId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter viewId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageNum" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "pageNum", c.Request.URL.Query(), &params.PageNum, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageNum: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTablesDstIdRecords(c, dstId, params)
}

// PatchTablesDstIdRecords operation middleware
func (siw *ServerInterfaceWrapper) PatchTablesDstIdRecords(c *gin.Context) {

	var err error

	// ------------- Path parameter "dstId" -------------
	var dstId string

	err = runtime.BindStyledParameterWithOptions("simple", "dstId", c.Param("dstId"), &dstId, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter dstId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params PatchTablesDstIdRecordsParams

	// ------------- Optional query parameter "viewId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "viewId", c.Request.URL.Query(), &params.ViewId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter viewId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PatchTablesDstIdRecords(c, dstId, params)
}

// PostTablesDstIdRecords operation middleware
func (siw *ServerInterfaceWrapper) PostTablesDstIdRecords(c *gin.Context) {

	var err error

	// ------------- Path parameter "dstId" -------------
	var dstId string

	err = runtime.BindStyledParameterWithOptions("simple", "dstId", c.Param("dstId"), &dstId, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter dstId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params PostTablesDstIdRecordsParams

	// ------------- Optional query parameter "viewId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "viewId", c.Request.URL.Query(), &params.ViewId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter viewId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostTablesDstIdRecords(c, dstId, params)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.DELETE(options.BaseURL+"/tables/:dstId/records", wrapper.DeleteTablesDstIdRecords)
	router.GET(options.BaseURL+"/tables/:dstId/records", wrapper.GetTablesDstIdRecords)
	router.PATCH(options.BaseURL+"/tables/:dstId/records", wrapper.PatchTablesDstIdRecords)
	router.POST(options.BaseURL+"/tables/:dstId/records", wrapper.PostTablesDstIdRecords)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xYQU8bRxT+K6vXHqexaUkPvoVAKquFWkDUA+Iw7D7sCbszy8wsxUU+NJXKIVVz76FV",
	"1T9AoiJcUchfmP1H1czaeO0dg6FgpWpOMTNv3vvmm/e99zZHEIokFRy5VtA4AhV2MKHu51OJVOM6hkJG",
	"ah33M1TarqdSpCg1Q2cli337k2lMVNVil2FcGNAoYpoJTuNWyULLDAlEqELJUrsNDTC/mPP85/zY9INP",
	"AtM3f5tTc2FOAvPOXJpzc2r+IoE5s0v5sdvq56+t5Z/mxFyYi/yVObV/nOevrdmJeWf6+femDwR0N0Vo",
	"gNh5gaGGXo+AxP2MSYygsTXEul2xI5Aw3iwuuHC1S6Wk3YqTISU+L8sY46ykNidoHThTWjLevguk5myg",
	"VCq4wiqqBJWibfRCUVkYoirD3BEiRsodlErEFSmFnB4pFFE5DOMa2yjtwQg1ZfEUOqbim2DDuR/Z+yhp",
	"0TbjtMjGSXQdqlaFRN9dCaS0jWtZ4vhinCX25+h1SjexhhvsO+cmoYcDy3qd3HBOC03jMff1qtnEhYeg",
	"SlGHjsjVdXw03JgTPvl/LHEXGvBRbVRaaoO6UtukO/Eg06D3L3Tk/CxTTadDG9Wd2ZE9s2eqwBxvpXy4",
	"zk8pc9x97pEfAtpuNyNv+ru9NZrMIIChGzIkaQR07KpTmS94qlA+VsQ9EJkfOfeDJkPv3dLmCEixcATI",
	"rQi2YIPxdoybeKiBwOCfYm0DY3uGwGoWa3b111qW7KAEAk8zKZGHXSDQQhkit7vLVOMmS6xSnmhNw05S",
	"rK/i8FQHw70dcQgE1qm2iAk8X//KOukIbs+tJJTFJRKnvAazD+E4GFhOpX2QGNV66Vp19MS1kl0hE6qL",
	"avD5IvhqyGwtuYJh2EW8b5Wl0S0wTOlPo4z0cfDchZjXRHKb69/pOvcxUVhLxneFw8R0bPe+YXssWImY",
	"FjJYouEe8ih40moCgQOUqhiwFh7VH9UtCJEipymDBnzmlqz+dceRU3NlQtWOIqWbUa9WIjZyE4P9ZVlz",
	"xcLyMpgkXK6qZXtqvVRWJE1Qo1TQ2DoCZlHYUMPcb4ALA+WbFw9R1EYf69uFMSq9JKJuMTlwbXVq3zZN",
	"YxY6bLUXqqhII1fXFWHvkNYbfxQLzS0U7cex8mm9/lAYBk3OgRgflb/+0j7j4j2GHh/OPCGXaBRc0ULg",
	"8TxjN7lGyWkcbKA8QBm4A04wKksSKrv26+EP9yFwbvr5y/ynsS8A+zFxFuQvzYl54wx+zF/Z8kTb6qox",
	"KtjuEWijrub3F6jnltxk4Gc/Q9kdOTpg+K3zdOuTpdlvdDbCXZrFGhqP7eQ58xx6XYxi0vSEWLjB5/YD",
	"6qk6ML6XWlqsL84v9prQwTOR8ej9VPFv9ls//yE/9ul4FgmnVIedqohbdvk/IOMH6m7eKWrO3e1DX7uT",
	"In41b8yFuTRvvZ3t7ZgozOkUUQjlaWwtofT/VxLe/+qcSRIL85REATP6oItJXfxuLs2ZnfnuqArnzvkv",
	"sjyTMTSgRlNWO1iA3nbvnwAAAP//cZcoGicXAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
