// Package mwsgptclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package mwsgptclient

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
)

// Defines values for ChatChoiceFinishReason.
const (
	ChatChoiceFinishReasonContentFilter ChatChoiceFinishReason = "content_filter"
	ChatChoiceFinishReasonLength        ChatChoiceFinishReason = "length"
	ChatChoiceFinishReasonStop          ChatChoiceFinishReason = "stop"
)

// Valid indicates whether the value is a known member of the ChatChoiceFinishReason enum.
func (e ChatChoiceFinishReason) Valid() bool {
	switch e {
	case ChatChoiceFinishReasonContentFilter:
		return true
	case ChatChoiceFinishReasonLength:
		return true
	case ChatChoiceFinishReasonStop:
		return true
	default:
		return false
	}
}

// Defines values for ChatCompletionResponseObject.
const (
	ChatCompletion ChatCompletionResponseObject = "chat.completion"
)

// Valid indicates whether the value is a known member of the ChatCompletionResponseObject enum.
func (e ChatCompletionResponseObject) Valid() bool {
	switch e {
	case ChatCompletion:
		return true
	default:
		return false
	}
}

// Defines values for ChatMessageRole.
const (
	Assistant ChatMessageRole = "assistant"
	System    ChatMessageRole = "system"
	User      ChatMessageRole = "user"
)

// Valid indicates whether the value is a known member of the ChatMessageRole enum.
func (e ChatMessageRole) Valid() bool {
	switch e {
	case Assistant:
		return true
	case System:
		return true
	case User:
		return true
	default:
		return false
	}
}

// Defines values for CompletionChoiceFinishReason.
const (
	CompletionChoiceFinishReasonLength CompletionChoiceFinishReason = "length"
	CompletionChoiceFinishReasonStop   CompletionChoiceFinishReason = "stop"
)

// Valid indicates whether the value is a known member of the CompletionChoiceFinishReason enum.
func (e CompletionChoiceFinishReason) Valid() bool {
	switch e {
	case CompletionChoiceFinishReasonLength:
		return true
	case CompletionChoiceFinishReasonStop:
		return true
	default:
		return false
	}
}

// Defines values for CompletionResponseObject.
const (
	TextCompletion CompletionResponseObject = "text_completion"
)

// Valid indicates whether the value is a known member of the CompletionResponseObject enum.
func (e CompletionResponseObject) Valid() bool {
	switch e {
	case TextCompletion:
		return true
	default:
		return false
	}
}

// Defines values for EmbeddingDataObject.
const (
	Embedding EmbeddingDataObject = "embedding"
)

// Valid indicates whether the value is a known member of the EmbeddingDataObject enum.
func (e EmbeddingDataObject) Valid() bool {
	switch e {
	case Embedding:
		return true
	default:
		return false
	}
}

// Defines values for EmbeddingsResponseObject.
const (
	List EmbeddingsResponseObject = "list"
)

// Valid indicates whether the value is a known member of the EmbeddingsResponseObject enum.
func (e EmbeddingsResponseObject) Valid() bool {
	switch e {
	case List:
		return true
	default:
		return false
	}
}

// Defines values for ModelObject.
const (
	ModelObjectModel ModelObject = "model"
)

// Valid indicates whether the value is a known member of the ModelObject enum.
func (e ModelObject) Valid() bool {
	switch e {
	case ModelObjectModel:
		return true
	default:
		return false
	}
}

// ChatChoice defines model for ChatChoice.
type ChatChoice struct {
	FinishReason *ChatChoiceFinishReason `json:"finish_reason,omitempty"`
	Index        *int                    `json:"index,omitempty"`
	Message      *ChatMessage            `json:"message,omitempty"`
}

// ChatChoiceFinishReason defines model for ChatChoice.FinishReason.
type ChatChoiceFinishReason string

// ChatCompletionRequest defines model for ChatCompletionRequest.
type ChatCompletionRequest struct {
	// FrequencyPenalty Штраф за использование частых токенов
	FrequencyPenalty *float32 `json:"frequency_penalty,omitempty"`

	// MaxTokens Максимальное количество возвращаемых токенов
	MaxTokens *int `json:"max_tokens,omitempty"`

	// Messages Массив сообщений
	Messages []ChatMessage `json:"messages"`

	// Model Модель для обработки текста
	Model string `json:"model"`

	// N Количество вариантов ответов
	N *int `json:"n,omitempty"`

	// PresencePenalty Штраф за повторение токенов из истории
	PresencePenalty *float32 `json:"presence_penalty,omitempty"`

	// Temperature Параметр случайности вывода (0.0 - детерминированный, 1.0 - более случайный)
	Temperature *float32 `json:"temperature,omitempty"`
}

// ChatCompletionResponse defines model for ChatCompletionResponse.
type ChatCompletionResponse struct {
	Choices *[]ChatChoice                 `json:"choices,omitempty"`
	Created *int64                        `json:"created,omitempty"`
	Id      *string                       `json:"id,omitempty"`
	Model   *string                       `json:"model,omitempty"`
	Object  *ChatCompletionResponseObject `json:"object,omitempty"`
	Usage   *Usage                        `json:"usage,omitempty"`
}

// ChatCompletionResponseObject defines model for ChatCompletionResponse.Object.
type ChatCompletionResponseObject string

// ChatMessage defines model for ChatMessage.
type ChatMessage struct {
	// Content Содержание сообщения
	Content string `json:"content"`

	// Role Роль отправителя
	Role ChatMessageRole `json:"role"`
}

// ChatMessageRole Роль отправителя
type ChatMessageRole string

// CompletionChoice defines model for CompletionChoice.
type CompletionChoice struct {
	FinishReason *CompletionChoiceFinishReason `json:"finish_reason,omitempty"`
	Index        *int                          `json:"index,omitempty"`

	// Text Сгенерированный текст
	Text *string `json:"text,omitempty"`
}

// CompletionChoiceFinishReason defines model for CompletionChoice.FinishReason.
type CompletionChoiceFinishReason string

// CompletionRequest defines model for CompletionRequest.
type CompletionRequest struct {
	FrequencyPenalty *float32 `json:"frequency_penalty,omitempty"`

	// MaxTokens Максимальное количество возвращаемых токенов
	MaxTokens *int `json:"max_tokens,omitempty"`

	// Model Модель для генерации
	Model           string   `json:"model"`
	PresencePenalty *float32 `json:"presence_penalty,omitempty"`

	// Prompt Текст запроса
	Prompt string `json:"prompt"`

	// Stop Условия остановки генерации
	Stop        *[]string `json:"stop,omitempty"`
	Temperature *float32  `json:"temperature,omitempty"`

	// TopP Альтернативный способ контроля случайности
	TopP *float32 `json:"top_p,omitempty"`
}

// CompletionResponse defines model for CompletionResponse.
type CompletionResponse struct {
	Choices *[]CompletionChoice       `json:"choices,omitempty"`
	Created *int64                    `json:"created,omitempty"`
	Id      *string                   `json:"id,omitempty"`
	Model   *string                   `json:"model,omitempty"`
	Object  *CompletionResponseObject `json:"object,omitempty"`
	Usage   *Usage                    `json:"usage,omitempty"`
}

// CompletionResponseObject defines model for CompletionResponse.Object.
type CompletionResponseObject string

// EmbeddingData defines model for EmbeddingData.
type EmbeddingData struct {
	// Embedding Векторное представление текста
	Embedding *[]float32           `json:"embedding,omitempty"`
	Index     *int                 `json:"index,omitempty"`
	Object    *EmbeddingDataObject `json:"object,omitempty"`
}

// EmbeddingDataObject defines model for EmbeddingData.Object.
type EmbeddingDataObject string

// EmbeddingsRequest defines model for EmbeddingsRequest.
type EmbeddingsRequest struct {
	// Input Текст для преобразования в эмбеддинг
	Input string `json:"input"`

	// Model Модель для эмбеддинга
	Model string `json:"model"`
}

// EmbeddingsResponse defines model for EmbeddingsResponse.
type EmbeddingsResponse struct {
	Data   *[]EmbeddingData          `json:"data,omitempty"`
	Model  *string                   `json:"model,omitempty"`
	Object *EmbeddingsResponseObject `json:"object,omitempty"`
	Usage  *Usage                    `json:"usage,omitempty"`
}

// EmbeddingsResponseObject defines model for EmbeddingsResponse.Object.
type EmbeddingsResponseObject string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		Code    *string `json:"code,omitempty"`
		Message *string `json:"message,omitempty"`
		Type    *string `json:"type,omitempty"`
	} `json:"error"`
}

// Model defines model for Model.
type Model struct {
	// Created Unix timestamp создания
	Created int64 `json:"created"`

	// Id Идентификатор модели
	Id     string      `json:"id"`
	Object ModelObject `json:"object"`

	// OwnedBy Владелец модели
	OwnedBy string `json:"owned_by"`
}

// ModelObject defines model for Model.Object.
type ModelObject string

// ModelsResponse defines model for ModelsResponse.
type ModelsResponse struct {
	Data []Model `json:"data"`
}

// Usage defines model for Usage.
type Usage struct {
	// CompletionTokens Количество токенов в ответе
	CompletionTokens *int `json:"completion_tokens,omitempty"`

	// PromptTokens Количество токенов в запросе
	PromptTokens *int `json:"prompt_tokens,omitempty"`

	// TotalTokens Общее количество токенов
	TotalTokens *int `json:"total_tokens,omitempty"`
}

// PostChatCompletionsJSONRequestBody defines body for PostChatCompletions for application/json ContentType.
type PostChatCompletionsJSONRequestBody = ChatCompletionRequest

// PostCompletionsJSONRequestBody defines body for PostCompletions for application/json ContentType.
type PostCompletionsJSONRequestBody = CompletionRequest

// PostEmbeddingsJSONRequestBody defines body for PostEmbeddings for application/json ContentType.
type PostEmbeddingsJSONRequestBody = EmbeddingsRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PostChatCompletionsWithBody request with any body
	PostChatCompletionsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostChatCompletions(ctx context.Context, body PostChatCompletionsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostCompletionsWithBody request with any body
	PostCompletionsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostCompletions(ctx context.Context, body PostCompletionsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostEmbeddingsWithBody request with any body
	PostEmbeddingsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostEmbeddings(ctx context.Context, body PostEmbeddingsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetModels request
	GetModels(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PostChatCompletionsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostChatCompletionsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostChatCompletions(ctx context.Context, body PostChatCompletionsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostChatCompletionsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostCompletionsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostCompletionsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostCompletions(ctx context.Context, body PostCompletionsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostCompletionsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostEmbeddingsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostEmbeddingsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostEmbeddings(ctx context.Context, body PostEmbeddingsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostEmbeddingsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetModels(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetModelsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPostChatCompletionsRequest calls the generic PostChatCompletions builder with application/json body
func NewPostChatCompletionsRequest(server string, body PostChatCompletionsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostChatCompletionsRequestWithBody(server, "application/json", bodyReader)
}

// NewPostChatCompletionsRequestWithBody generates requests for PostChatCompletions with any type of body
func NewPostChatCompletionsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/chat/completions")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostCompletionsRequest calls the generic PostCompletions builder with application/json body
func NewPostCompletionsRequest(server string, body PostCompletionsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostCompletionsRequestWithBody(server, "application/json", bodyReader)
}

// NewPostCompletionsRequestWithBody generates requests for PostCompletions with any type of body
func NewPostCompletionsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/completions")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostEmbeddingsRequest calls the generic PostEmbeddings builder with application/json body
func NewPostEmbeddingsRequest(server string, body PostEmbeddingsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostEmbeddingsRequestWithBody(server, "application/json", bodyReader)
}

// NewPostEmbeddingsRequestWithBody generates requests for PostEmbeddings with any type of body
func NewPostEmbeddingsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/embeddings")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetModelsRequest generates requests for GetModels
func NewGetModelsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/models")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PostChatCompletionsWithBodyWithResponse request with any body
	PostChatCompletionsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostChatCompletionsResponse, error)

	PostChatCompletionsWithResponse(ctx context.Context, body PostChatCompletionsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostChatCompletionsResponse, error)

	// PostCompletionsWithBodyWithResponse request with any body
	PostCompletionsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostCompletionsResponse, error)

	PostCompletionsWithResponse(ctx context.Context, body PostCompletionsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostCompletionsResponse, error)

	// PostEmbeddingsWithBodyWithResponse request with any body
	PostEmbeddingsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostEmbeddingsResponse, error)

	PostEmbeddingsWithResponse(ctx context.Context, body PostEmbeddingsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostEmbeddingsResponse, error)

	// GetModelsWithResponse request
	GetModelsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetModelsResponse, error)
}

type PostChatCompletionsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ChatCompletionResponse
	JSON400      *ErrorResponse
	JSON401      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostChatCompletionsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostChatCompletionsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostCompletionsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CompletionResponse
	JSON400      *ErrorResponse
	JSON401      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostCompletionsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostCompletionsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostEmbeddingsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EmbeddingsResponse
	JSON400      *ErrorResponse
	JSON401      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostEmbeddingsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostEmbeddingsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetModelsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ModelsResponse
	JSON401      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetModelsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetModelsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// PostChatCompletionsWithBodyWithResponse request with arbitrary body returning *PostChatCompletionsResponse
func (c *ClientWithResponses) PostChatCompletionsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostChatCompletionsResponse, error) {
	rsp, err := c.PostChatCompletionsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostChatCompletionsResponse(rsp)
}

func (c *ClientWithResponses) PostChatCompletionsWithResponse(ctx context.Context, body PostChatCompletionsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostChatCompletionsResponse, error) {
	rsp, err := c.PostChatCompletions(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostChatCompletionsResponse(rsp)
}

// PostCompletionsWithBodyWithResponse request with arbitrary body returning *PostCompletionsResponse
func (c *ClientWithResponses) PostCompletionsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostCompletionsResponse, error) {
	rsp, err := c.PostCompletionsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostCompletionsResponse(rsp)
}

func (c *ClientWithResponses) PostCompletionsWithResponse(ctx context.Context, body PostCompletionsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostCompletionsResponse, error) {
	rsp, err := c.PostCompletions(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostCompletionsResponse(rsp)
}

// PostEmbeddingsWithBodyWithResponse request with arbitrary body returning *PostEmbeddingsResponse
func (c *ClientWithResponses) PostEmbeddingsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostEmbeddingsResponse, error) {
	rsp, err := c.PostEmbeddingsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostEmbeddingsResponse(rsp)
}

func (c *ClientWithResponses) PostEmbeddingsWithResponse(ctx context.Context, body PostEmbeddingsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostEmbeddingsResponse, error) {
	rsp, err := c.PostEmbeddings(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostEmbeddingsResponse(rsp)
}

// GetModelsWithResponse request returning *GetModelsResponse
func (c *ClientWithResponses) GetModelsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetModelsResponse, error) {
	rsp, err := c.GetModels(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetModelsResponse(rsp)
}

// ParsePostChatCompletionsResponse parses an HTTP response from a PostChatCompletionsWithResponse call
func ParsePostChatCompletionsResponse(rsp *http.Response) (*PostChatCompletionsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostChatCompletionsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ChatCompletionResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostCompletionsResponse parses an HTTP response from a PostCompletionsWithResponse call
func ParsePostCompletionsResponse(rsp *http.Response) (*PostCompletionsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostCompletionsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CompletionResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostEmbeddingsResponse parses an HTTP response from a PostEmbeddingsWithResponse call
func ParsePostEmbeddingsResponse(rsp *http.Response) (*PostEmbeddingsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostEmbeddingsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EmbeddingsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetModelsResponse parses an HTTP response from a GetModelsWithResponse call
func ParseGetModelsResponse(rsp *http.Response) (*GetModelsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetModelsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ModelsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
