// Package tableshttp provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package tableshttp

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// Defines values for CreateFieldRequestType.
const (
	CreateFieldRequestTypeAttachment   CreateFieldRequestType = "Attachment"
	CreateFieldRequestTypeCheckbox     CreateFieldRequestType = "Checkbox"
	CreateFieldRequestTypeCurrency     CreateFieldRequestType = "Currency"
	CreateFieldRequestTypeDateTime     CreateFieldRequestType = "DateTime"
	CreateFieldRequestTypeEmail        CreateFieldRequestType = "Email"
	CreateFieldRequestTypeMember       CreateFieldRequestType = "Member"
	CreateFieldRequestTypeMultiSelect  CreateFieldRequestType = "MultiSelect"
	CreateFieldRequestTypeNumber       CreateFieldRequestType = "Number"
	CreateFieldRequestTypePercent      CreateFieldRequestType = "Percent"
	CreateFieldRequestTypePhone        CreateFieldRequestType = "Phone"
	CreateFieldRequestTypeRating       CreateFieldRequestType = "Rating"
	CreateFieldRequestTypeSingleSelect CreateFieldRequestType = "SingleSelect"
	CreateFieldRequestTypeSingleText   CreateFieldRequestType = "SingleText"
	CreateFieldRequestTypeText         CreateFieldRequestType = "Text"
	CreateFieldRequestTypeURL          CreateFieldRequestType = "URL"
)

// Valid indicates whether the value is a known member of the CreateFieldRequestType enum.
func (e CreateFieldRequestType) Valid() bool {
	switch e {
	case CreateFieldRequestTypeAttachment:
		return true
	case CreateFieldRequestTypeCheckbox:
		return true
	case CreateFieldRequestTypeCurrency:
		return true
	case CreateFieldRequestTypeDateTime:
		return true
	case CreateFieldRequestTypeEmail:
		return true
	case CreateFieldRequestTypeMember:
		return true
	case CreateFieldRequestTypeMultiSelect:
		return true
	case CreateFieldRequestTypeNumber:
		return true
	case CreateFieldRequestTypePercent:
		return true
	case CreateFieldRequestTypePhone:
		return true
	case CreateFieldRequestTypeRating:
		return true
	case CreateFieldRequestTypeSingleSelect:
		return true
	case CreateFieldRequestTypeSingleText:
		return true
	case CreateFieldRequestTypeText:
		return true
	case CreateFieldRequestTypeURL:
		return true
	default:
		return false
	}
}

// Defines values for TableFieldType.
const (
	TableFieldTypeAttachment   TableFieldType = "Attachment"
	TableFieldTypeCheckbox     TableFieldType = "Checkbox"
	TableFieldTypeCurrency     TableFieldType = "Currency"
	TableFieldTypeDateTime     TableFieldType = "DateTime"
	TableFieldTypeEmail        TableFieldType = "Email"
	TableFieldTypeMember       TableFieldType = "Member"
	TableFieldTypeMultiSelect  TableFieldType = "MultiSelect"
	TableFieldTypeNumber       TableFieldType = "Number"
	TableFieldTypePercent      TableFieldType = "Percent"
	TableFieldTypePhone        TableFieldType = "Phone"
	TableFieldTypeRating       TableFieldType = "Rating"
	TableFieldTypeSingleSelect TableFieldType = "SingleSelect"
	TableFieldTypeSingleText   TableFieldType = "SingleText"
	TableFieldTypeText         TableFieldType = "Text"
	TableFieldTypeURL          TableFieldType = "URL"
)

// Valid indicates whether the value is a known member of the TableFieldType enum.
func (e TableFieldType) Valid() bool {
	switch e {
	case TableFieldTypeAttachment:
		return true
	case TableFieldTypeCheckbox:
		return true
	case TableFieldTypeCurrency:
		return true
	case TableFieldTypeDateTime:
		return true
	case TableFieldTypeEmail:
		return true
	case TableFieldTypeMember:
		return true
	case TableFieldTypeMultiSelect:
		return true
	case TableFieldTypeNumber:
		return true
	case TableFieldTypePercent:
		return true
	case TableFieldTypePhone:
		return true
	case TableFieldTypeRating:
		return true
	case TableFieldTypeSingleSelect:
		return true
	case TableFieldTypeSingleText:
		return true
	case TableFieldTypeText:
		return true
	case TableFieldTypeURL:
		return true
	default:
		return false
	}
}

// CreateFieldRequest defines model for CreateFieldRequest.
type CreateFieldRequest struct {
	Name     string                  `json:"name"`
	Property *map[string]interface{} `json:"property,omitempty"`
	Type     CreateFieldRequestType  `json:"type"`
}

// CreateFieldRequestType defines model for CreateFieldRequest.Type.
type CreateFieldRequestType string

// CreateRecordsRequest defines model for CreateRecordsRequest.
type CreateRecordsRequest struct {
	Records []struct {
		// Fields Ключи - имена полей, значения - данные для записи
		Fields map[string]interface{} `json:"fields"`
	} `json:"records"`
}

// DeleteRecordsRequest defines model for DeleteRecordsRequest.
type DeleteRecordsRequest struct {
	RecordIds []string `json:"recordIds"`
}

// DeleteRecordsResponse defines model for DeleteRecordsResponse.
type DeleteRecordsResponse struct {
	Message *string `json:"message,omitempty"`
	Success *bool   `json:"success,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    int     `json:"code"`
	Details *string `json:"details,omitempty"`
	Message string  `json:"message"`
}

// FieldResponse defines model for FieldResponse.
type FieldResponse struct {
	Id   string `json:"id"`
	Name string `json:"name"`
	Type string `json:"type"`
}

// Pagination defines model for Pagination.
type Pagination struct {
	HasMore  bool `json:"hasMore"`
	PageNum  int  `json:"pageNum"`
	PageSize int  `json:"pageSize"`
	Total    int  `json:"total"`
}

// RecordsResponse defines model for RecordsResponse.
type RecordsResponse struct {
	Records []TableRecord `json:"records"`
}

// SuccessResponse defines model for SuccessResponse.
type SuccessResponse struct {
	Message *string `json:"message,omitempty"`
	Success *bool   `json:"success,omitempty"`
}

// TableDataResponse defines model for TableDataResponse.
type TableDataResponse struct {
	Fields     []TableField  `json:"fields"`
	Pagination Pagination    `json:"pagination"`
	Records    []TableRecord `json:"records"`
	TableId    string        `json:"tableId"`
	TableName  *string       `json:"tableName,omitempty"`
}

// TableField defines model for TableField.
type TableField struct {
	Description *string                 `json:"description,omitempty"`
	Id          string                  `json:"id"`
	Name        string                  `json:"name"`
	Property    *map[string]interface{} `json:"property,omitempty"`
	Type        TableFieldType          `json:"type"`
}

// TableFieldType defines model for TableField.Type.
type TableFieldType string

// TableRecord defines model for TableRecord.
type TableRecord struct {
	CreatedAt *int64                 `json:"createdAt,omitempty"`
	Fields    map[string]interface{} `json:"fields"`
	RecordId  string                 `json:"recordId"`
	UpdatedAt *int64                 `json:"updatedAt,omitempty"`
}

// UpdateRecordsRequest defines model for UpdateRecordsRequest.
type UpdateRecordsRequest struct {
	Records []struct {
		Fields   map[string]interface{} `json:"fields"`
		RecordId string                 `json:"recordId"`
	} `json:"records"`
}

// PostTablesDstIdFieldsParams defines parameters for PostTablesDstIdFields.
type PostTablesDstIdFieldsParams struct {
	SpaceId string `form:"spaceId" json:"spaceId"`
}

// DeleteTablesDstIdFieldsFieldIdParams defines parameters for DeleteTablesDstIdFieldsFieldId.
type DeleteTablesDstIdFieldsFieldIdParams struct {
	SpaceId string `form:"spaceId" json:"spaceId"`
}

// GetTablesDstIdRecordsParams defines parameters for GetTablesDstIdRecords.
type GetTablesDstIdRecordsParams struct {
	ViewId   *string `form:"viewId,omitempty" json:"viewId,omitempty"`
	PageSize *int    `form:"pageSize,omitempty" json:"pageSize,omitempty"`
	PageNum  *int    `form:"pageNum,omitempty" json:"pageNum,omitempty"`
}

// PatchTablesDstIdRecordsParams defines parameters for PatchTablesDstIdRecords.
type PatchTablesDstIdRecordsParams struct {
	ViewId *string `form:"viewId,omitempty" json:"viewId,omitempty"`
}

// PostTablesDstIdRecordsParams defines parameters for PostTablesDstIdRecords.
type PostTablesDstIdRecordsParams struct {
	ViewId *string `form:"viewId,omitempty" json:"viewId,omitempty"`
}

// PatchTablesDstIdViewsViewIdFieldsFieldIdIndexJSONBody defines parameters for PatchTablesDstIdViewsViewIdFieldsFieldIdIndex.
type PatchTablesDstIdViewsViewIdFieldsFieldIdIndexJSONBody struct {
	Index int `json:"index"`
}

// PostTablesDstIdFieldsJSONRequestBody defines body for PostTablesDstIdFields for application/json ContentType.
type PostTablesDstIdFieldsJSONRequestBody = CreateFieldRequest

// DeleteTablesDstIdRecordsJSONRequestBody defines body for DeleteTablesDstIdRecords for application/json ContentType.
type DeleteTablesDstIdRecordsJSONRequestBody = DeleteRecordsRequest

// PatchTablesDstIdRecordsJSONRequestBody defines body for PatchTablesDstIdRecords for application/json ContentType.
type PatchTablesDstIdRecordsJSONRequestBody = UpdateRecordsRequest

// PostTablesDstIdRecordsJSONRequestBody defines body for PostTablesDstIdRecords for application/json ContentType.
type PostTablesDstIdRecordsJSONRequestBody = CreateRecordsRequest

// PatchTablesDstIdViewsViewIdFieldsFieldIdIndexJSONRequestBody defines body for PatchTablesDstIdViewsViewIdFieldsFieldIdIndex for application/json ContentType.
type PatchTablesDstIdViewsViewIdFieldsFieldIdIndexJSONRequestBody PatchTablesDstIdViewsViewIdFieldsFieldIdIndexJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Создать поле в таблице
	// (POST /tables/{dstId}/fields)
	PostTablesDstIdFields(c *gin.Context, dstId string, params PostTablesDstIdFieldsParams)
	// Удалить поле из таблицы
	// (DELETE /tables/{dstId}/fields/{fieldId})
	DeleteTablesDstIdFieldsFieldId(c *gin.Context, dstId string, fieldId string, params DeleteTablesDstIdFieldsFieldIdParams)
	// Удалить записи из таблицы
	// (DELETE /tables/{dstId}/records)
	DeleteTablesDstIdRecords(c *gin.Context, dstId string)
	// Получить записи таблицы
	// (GET /tables/{dstId}/records)
	GetTablesDstIdRecords(c *gin.Context, dstId string, params GetTablesDstIdRecordsParams)
	// Обновить записи в таблице
	// (PATCH /tables/{dstId}/records)
	PatchTablesDstIdRecords(c *gin.Context, dstId string, params PatchTablesDstIdRecordsParams)
	// Создать записи в таблице
	// (POST /tables/{dstId}/records)
	PostTablesDstIdRecords(c *gin.Context, dstId string, params PostTablesDstIdRecordsParams)
	// Изменить порядок поля в представлении
	// (PATCH /tables/{dstId}/views/{viewId}/fields/{fieldId}/index)
	PatchTablesDstIdViewsViewIdFieldsFieldIdIndex(c *gin.Context, dstId string, viewId string, fieldId string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// PostTablesDstIdFields operation middleware
func (siw *ServerInterfaceWrapper) PostTablesDstIdFields(c *gin.Context) {

	var err error

	// ------------- Path parameter "dstId" -------------
	var dstId string

	err = runtime.BindStyledParameterWithOptions("simple", "dstId", c.Param("dstId"), &dstId, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter dstId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params PostTablesDstIdFieldsParams

	// ------------- Required query parameter "spaceId" -------------

	if paramValue := c.Query("spaceId"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument spaceId is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "spaceId", c.Request.URL.Query(), &params.SpaceId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter spaceId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostTablesDstIdFields(c, dstId, params)
}

// DeleteTablesDstIdFieldsFieldId operation middleware
func (siw *ServerInterfaceWrapper) DeleteTablesDstIdFieldsFieldId(c *gin.Context) {

	var err error

	// ------------- Path parameter "dstId" -------------
	var dstId string

	err = runtime.BindStyledParameterWithOptions("simple", "dstId", c.Param("dstId"), &dstId, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter dstId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "fieldId" -------------
	var fieldId string

	err = runtime.BindStyledParameterWithOptions("simple", "fieldId", c.Param("fieldId"), &fieldId, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter fieldId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteTablesDstIdFieldsFieldIdParams

	// ------------- Required query parameter "spaceId" -------------

	if paramValue := c.Query("spaceId"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument spaceId is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "spaceId", c.Request.URL.Query(), &params.SpaceId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter spaceId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteTablesDstIdFieldsFieldId(c, dstId, fieldId, params)
}

// DeleteTablesDstIdRecords operation middleware
func (siw *ServerInterfaceWrapper) DeleteTablesDstIdRecords(c *gin.Context) {

	var err error

	// ------------- Path parameter "dstId" -------------
	var dstId string

	err = runtime.BindStyledParameterWithOptions("simple", "dstId", c.Param("dstId"), &dstId, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter dstId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteTablesDstIdRecords(c, dstId)
}

// GetTablesDstIdRecords operation middleware
func (siw *ServerInterfaceWrapper) GetTablesDstIdRecords(c *gin.Context) {

	var err error

	// ------------- Path parameter "dstId" -------------
	var dstId string

	err = runtime.BindStyledParameterWithOptions("simple", "dstId", c.Param("dstId"), &dstId, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter dstId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTablesDstIdRecordsParams

	// ------------- Optional query parameter "viewId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "viewId", c.Request.URL.Query(), &params.ViewId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter viewId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageNum" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "pageNum", c.Request.URL.Query(), &params.PageNum, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageNum: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTablesDstIdRecords(c, dstId, params)
}

// PatchTablesDstIdRecords operation middleware
func (siw *ServerInterfaceWrapper) PatchTablesDstIdRecords(c *gin.Context) {

	var err error

	// ------------- Path parameter "dstId" -------------
	var dstId string

	err = runtime.BindStyledParameterWithOptions("simple", "dstId", c.Param("dstId"), &dstId, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter dstId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params PatchTablesDstIdRecordsParams

	// ------------- Optional query parameter "viewId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "viewId", c.Request.URL.Query(), &params.ViewId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter viewId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PatchTablesDstIdRecords(c, dstId, params)
}

// PostTablesDstIdRecords operation middleware
func (siw *ServerInterfaceWrapper) PostTablesDstIdRecords(c *gin.Context) {

	var err error

	// ------------- Path parameter "dstId" -------------
	var dstId string

	err = runtime.BindStyledParameterWithOptions("simple", "dstId", c.Param("dstId"), &dstId, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter dstId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params PostTablesDstIdRecordsParams

	// ------------- Optional query parameter "viewId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "viewId", c.Request.URL.Query(), &params.ViewId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter viewId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostTablesDstIdRecords(c, dstId, params)
}

// PatchTablesDstIdViewsViewIdFieldsFieldIdIndex operation middleware
func (siw *ServerInterfaceWrapper) PatchTablesDstIdViewsViewIdFieldsFieldIdIndex(c *gin.Context) {

	var err error

	// ------------- Path parameter "dstId" -------------
	var dstId string

	err = runtime.BindStyledParameterWithOptions("simple", "dstId", c.Param("dstId"), &dstId, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter dstId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "viewId" -------------
	var viewId string

	err = runtime.BindStyledParameterWithOptions("simple", "viewId", c.Param("viewId"), &viewId, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter viewId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "fieldId" -------------
	var fieldId string

	err = runtime.BindStyledParameterWithOptions("simple", "fieldId", c.Param("fieldId"), &fieldId, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter fieldId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PatchTablesDstIdViewsViewIdFieldsFieldIdIndex(c, dstId, viewId, fieldId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/tables/:dstId/fields", wrapper.PostTablesDstIdFields)
	router.DELETE(options.BaseURL+"/tables/:dstId/fields/:fieldId", wrapper.DeleteTablesDstIdFieldsFieldId)
	router.DELETE(options.BaseURL+"/tables/:dstId/records", wrapper.DeleteTablesDstIdRecords)
	router.GET(options.BaseURL+"/tables/:dstId/records", wrapper.GetTablesDstIdRecords)
	router.PATCH(options.BaseURL+"/tables/:dstId/records", wrapper.PatchTablesDstIdRecords)
	router.POST(options.BaseURL+"/tables/:dstId/records", wrapper.PostTablesDstIdRecords)
	router.PATCH(options.BaseURL+"/tables/:dstId/views/:viewId/fields/:fieldId/index", wrapper.PatchTablesDstIdViewsViewIdFieldsFieldIdIndex)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xazW4btxN/FYH//3EbyW3Sg25JHBdCE9ewk/QQ+EDvjiUm+xWS61oVBCQp0BxS1Nei",
	"hxZFX8AJYlita+cVuG9UDKnV7mope5XasoPkJJkfM8Mf5zfDGWtA3CiIoxBCKUh7QITbg4Dqr7c5UAkr",
	"DHxvHZ4mICSOxjyKgUsGek1IA8DPgO7ehbAre6S91Go5RPZjIG0iJGdhlwydbFsfF48no63H4EqcNAMD",
	"AmESkPYjssHCrg/3YVcSh4w/zNgG+LjHIfcSX7LJX6tJsAWcOOR2wjmEbp84ZA24CyHOLlMJ91kAxCE3",
	"paRuLzDj9yDb1QP3yVa0SxyyTiVa7JAH63dRSC8Kcd+dgDKfbFYONnQIh6cJ4+Ch4RqO8aJ8cX5QA+k6",
	"uBH3xExQuZnHr0xCIKortvFS9DfqeUyyKKT+WmGF5Ak4xAPhchbjNGkT9as6Sn9OX6pR47OGGql/1IE6",
	"VvsN9U6dqCN1oP5yGuoQh9KXemqU7uHKt2pfHavj9JU6wD+O0j1ctq/eqVH6XI1I5ZhTmIxttcERsLBj",
	"Drg0maWc035FSAaJTcoy+FAX1M4UrBU/ndekTj2jRByFAqpWBSAE7YLVFJG4LoiimVtR5AMNtSkVjXc4",
	"j/hsTW7kFdWwUEIXOG70QFLmz4Bjpn1TaGjx+XobJONIMstA5lktyCJMZSILGqfbxTzinEnLNdplITU8",
	"mTarR8W9iIPtFhwS0y6sYswaoOOwAL/mflPAGBdusO+zWDleiZHy9H0yktQviW9Vl00dOTOqoDUT5EyO",
	"Y4PhTG+1Bab/c9gmbfK/Zp5HmuMk0rxPt/wxB/Ibew+GbxgmLIRG2uZlKulsbXn0rY+Cdv4qCPqOCr53",
	"mpyCl2rszvEuHCJxumOnoJ5btfNw6hYzMU4GUm5o6aibs5A3OFUgL6Uyi4nzBo+P4zlSK/gVHaOaNfSD",
	"xbupE+p2xAMqTeT58jqxxat6D5OKDVkutd5VEntz2DAjS+ceacPggVaxqHfZPMd/r+Ocx7sKV7JwO9I2",
	"Menj3LfsCWvc8ZiMeOMWdZ9A6DVurnWIQ3aAC/PMXLrWutZCI6IYQhoz0iZf6CHkv+xpcJo6TIjmwBOy",
	"4w2bOWxxZIBHyHSkQFDIWiSkdlOxjBtWstASU04DkMAFaT8aEIb6UUnm9W2iFZDimc0VmKhoxXss52kC",
	"vJ8LEjF1YU5Rm2YxCHkr8vrmERZKJDs6SBz7zNVnbD4WJqzlok6L5Ja6bFi+VzRMD5gMppH9vLV0bhaU",
	"X3JaebnWMCbqRHO91To3veUnrkXvLeo1ckww9wcB5X2sfv5QJ+oQi5n0RfrTpOhpqDeN9IXaV6/VkRql",
	"P6oDDCm0KybJTJBNlGR32eZAf3a8oUlS+Oavuq+pBSoOvGK2XrAfl+VsT3ReHiNKTnl+zjH9SLS4xzdf",
	"X65Hou7ri9O9GsnGSpSE3jQX/tRFPTp8mQsjdVhiQ/qqJhsKmbE2CdYL78Lzd/8Lir3WXkOt6Nu6KBuu",
	"srvfWKTuTiiBh9RvbADfAd7QG85w/UIjq677O6QLljfKVyAX5twzIvIOg++0pLl3FhoF+V4PtmniS9K+",
	"0XLmaFqcpsO0JSwqls6QeZGJo1rxf0odhdRxFVn8O2as9If0pY3HdSgcU+n2LIUGDn8ANL6g7GYtgxec",
	"3T7ltfdixG/qtTpWJ+qNNbPVKXKcesX3R0YJ63/sFlxu16DElSi4ryIvpsr+uVlhKXbQGUVzYHyy2glo",
	"stCDXd3MqpdkHqK8h1paqTHQ0XIW2R2Y0Owy2gz/gcBT/0jM8D/9lVrulOs99i7o4nLfB9DCKLPrF3U4",
	"/h1B3kpIn6V76q06UX+POwvpHlJNvUufqQP1Nn2uSfdG/+TgWI3MLwgqtEM9mtbG6RPukzZp0pg1d5bI",
	"cHP4bwAAAP//Bwpd27giAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
